### ISSUE TITLE
Possible bug in pagination.

### ISSUE THREAD

**Issue by pkaleta** [backbone-paginator/backbone-pageable#100]
@wyuenho it feels weird that `lastPage` is less than `firstPage` in case when page numbers are 1-based and `totalRecords` is 0:

https://github.com/wyuenho/backbone-pageable/blob/master/test/server-pageable.js#L142

Is it a bug?

Anyway this causes a bug in `backgrid-paginator`. When a collection is empty, the links to next and last page are not disabled: https://github.com/wyuenho/backgrid-paginator/blob/master/backgrid-paginator.js#L152

**Comment by wyuenho** [comment]
lastPage should probably be set back to null to indicate that value is temporarily meaningless. If you can help me with that it'll be great. Otherwise I'll deal with it sometime next week.
