### ISSUE TITLE
Do not reference Backbone git repo in npm dependencies

### ISSUE THREAD

**Issue by etreworgy** [backbone-paginator/backbone-pageable#102]
You're currently referencing the backbone git repo directly in your npm dependencies.  This isn't a good idea for an official release version because they might make changes on the master branch that aren't fully tested or aren't backwards compatible (and guess what, they currently have such a change!).

**Comment by wyuenho** [comment]
Which change have they introduced that breaks pageable?

**Comment by wyuenho** [comment]
BTW, pageable currently only works with Backbone master

**Comment by etreworgy** [comment]
They've made a change that is not backwards compatible with 1.0.0, specifically they no longer attach the options object to the View.  This doesn't break backbone-pageable necessarily but it does cause issues with my code (as I share Backbone as a dependency with backbone-pageable).  When I do an npm install I initially get the correct version of Backbone (1.0.0), but when npm installs backbone-pageable the cached version of Backbone seems to get replaced by Backbone master.  Because of this any future updates or installs causes Backbone master to get installed in place of 1.0.0.

Also backbone-pageable seems to work just fine with the release version of 1.0.0 and in all of this aside it seems like a bad idea to reference a development branch of a library in a published release.

**Comment by wyuenho** [comment]
pageable doesn't work with backbone 1.0.0, see #70 and #96.

I'm eagerly waiting for backbone 1.0.1, which hopefully jashkenas will release within a week.
