### ISSUE TITLE
Send server request on single page data sort order change

### ISSUE THREAD

**Issue by fulleron** [backbone-paginator/backbone-pageable#105]
Here's my situation - I'm using the data request to save user preferences about sort column and direction for this grid.

I understand that if there's only one page of data, the PageableCollection doesn't send request to re-retrieve data, which makes sense. However this doesn't give the server opportunity to remember user preference.

Is there a way to force server request, or send a custom request if none is required for data?

Hope this makes sense.
Thank you.

**Comment by wyuenho** [comment]
You can always force a fetch by passing {fetch: true} to any get*Page methods. Just calling fetch should work too most of the time. The only exception is when fetching under infinite mode. Since the last release, fetching will always add to the fullCollection.

**Comment by fulleron** [comment]
Thank you. I'm not calling get*Page methods directly, I just have `new Backgrid.Grid({collection:new PageableCollection})` style instantiation. 

It seems that I would need to reimplement `HeaderCell.sort()` and add `collection.fetch({reset: true, fetch: true})` ?

**Comment by wyuenho** [comment]
No you don't. Just instantiate the collection and assign the reference to a variable, and keep that reference around so you can call .fetch() or .get*Page().

**Comment by wyuenho** [comment]
You can save the direction of a column to the server now using backgrid's master. Ping me if it doesn't work for you.
