### ISSUE TITLE
Catching RangeErrors when refreshing the page

### ISSUE THREAD

**Issue by gibbster** [backbone-paginator/backbone-pageable#106]
Hi! I love your plugin; it's a pleasure to use.

One thing I haven't really come to grips with: I'm using the server mode pagination, and I'd like to update my paging buttons as I add and remove models from the collection.

What I ended up doing is something like this:

``` javascript
this.collection.create(newOrg, {
    success: function(model, xhr, options) {
        that.refresh();
    }
});
```

The refresh method refreshes the current page: `this.collection.getPage(this.collection.state.currentPage)`.

That works fine for adding new items, but I can run into trouble when removing items if that reduces the number of items on the current page to 0. From what I can tell, the `getPage` method calls the `fetch` method, which in turn triggers the `parse` method which calls `_checkState`, which fails with a `RangeError`.

What's the best way of dealing with this issue? The best I could come up with was to override the `parse` method, but that seems like overkill, and I get the feeling that I'm missing something.

Thanks again.

**Comment by gibbster** [comment]
Hi,

Any thoughts on this? I'd be happy to share more information, if you think that'll help. If I've missed something obvious in the documentation then I apologize: a link to get me going in the right direction would be greatly appreciated.

Thanks

**Comment by wyuenho** [comment]
Just listen to the `add` and `remove` events from pageable and update your paging buttons.
