### ISSUE TITLE
Anyway to avoid paging?

### ISSUE THREAD

**Issue by josx** [backbone-paginator/backbone-pageable#110]
I need to use the same collections to pagintate and also in some places not pagination at all?
is there anyway i can accomplish this?

**Comment by wyuenho** [comment]
backbone-pageable collection is just a plain backbone collection, if you don't want to page, just don't call any get*Page methods and use it as is. You can override fetch by giving it a data hash with a given url if the default behavior is getting in the way.

http://backbonejs.org/#Collection-fetch
