### ISSUE TITLE
browser-crashes-after-a-few-pagination-applied-in-pageable-collection

### ISSUE THREAD

**Issue by Koka5** [backbone-paginator/backbone-pageable#111]
I have a paginator which can move our pages in the came from pageable collection.

I am working upon server side mode of backbone pageable collection.

The problem is when i paginate 5-6 times from the paginator. Chrome got crashed as it increases the memory for storing current collection. And perhaps it is not destroying the previously stored collection.

I am doing the following to solve the problem :

this.collection.getPage(pageNo).success(function(result) {
              this.collection.remove();
            });

I was expecting this.collection.remove() to clear the memory used. But it actually doesn't. But the above does not solve the problem.

Has anybody find this problem earlier? How did you solved the problem?

**Comment by wyuenho** [comment]
The models are destroyed and not retained under server mode. Client mode and infinite mode caches them until you destroy the collection altogether and remove the views referencing the collection.

Collection$#remove also doesn't remove the collection. It's a method to remove an element from the collection. You have to delete it.
