### ISSUE TITLE
Removing element from the PageableCollection.

### ISSUE THREAD

**Issue by etugarev** [backbone-paginator/backbone-pageable#113]
Hello, I'm relatively new to Backbone, I'm trying to use a PageableCollection in my application. Could someone please point me out of what am I doing wrong. 

I have a collection and a model defined like this:

```
var VoteList = Backbone.PageableCollection.extend({
    model: Vote,
    url: config.service + 'votes'
});

var Vote = Backbone.Model.extend({
    url: function () {
        return config.service + 'vote/' + this.id;
    }
});
```

later in the application:

this.collections.voteList = new VoteList([], {mode: "client", state: {pageSize: 12}});
....
_this.collections.voteList.remove(options.model);

PageableCollection.remove() method fires a DELETE event which uses the URL of VoteList collection(?) to access a web service which in turn produces an error 405 as DELETE method is supposed to have an {id}

```
@DELETE
@Path("/voting/{id}")
@Consumes({MediaType.APPLICATION_JSON})
public void deleteVoting(@PathParam("id") Integer id) {
    log.info("deleting " + id.toString());
}
```

When I remove pagination just by instantiating normal Backbone.Collection 

var VoteList = Backbone.Collection.extend({});

everything works as expected, Backbone uses a model url with the id. So my question is how to make PageableCollection to behave the same way?

**Comment by wyuenho** [comment]
Use Backbone master. This is a known bug in Backbone 1.0 See #70.
