### ISSUE TITLE
Constructor should not modify array passed as argument

### ISSUE THREAD

**Issue by nynexman4464** [backbone-paginator/backbone-pageable#114]
When a pagable collection is in `client` mode, the constructor modifies the `model` array passed in as an argument to the constructor of the collection. (on line 312)

This has burned me several times when I was attempting to create a new collection from an existing array.  My original array gets modified, and is useless thereafter.

This is a severe problem when you attempt to `clone` a pageable collection.  The `clone` method passes in the collection's internal `models` array to the constructor, meaning that cloning a pagable collection will actually result in the _original_ collection being modified!

The `model` argument should be cloned to avoid ever modifying the original argument.

**Comment by wyuenho** [comment]
This should be an easy fix. File me a PR?

**Comment by wyuenho** [comment]
On second thought, the same happens to Backbone.Collection as well. Unfortunately there's no way to do a deep copy in JS. Backbone.Collection#clone only does a shallow copy and give you a new collection reference that still references the underlying models array.

https://github.com/jashkenas/backbone/blob/master/backbone.js#L894
https://github.com/jashkenas/backbone/blob/master/backbone.js#L668

I'm going to close this one and have PageableCollection remain highly compatible with Backbone.Collection.

**Comment by nynexman4464** [comment]
Backbone does a shallow copy, that is fine.  It's documented and makes sense.
Pageable is not doing a copy at all! it is modifying the original array!  This is a major issue and needs to be addressed!

**Comment by nynexman4464** [comment]
Here's an example that illustrates the problem

```
var collection1 = [],
collection2 = [],
len=50;
for(var i=0;i<len;++i){
    collection1.push(i);
    collection2.push(i);
}

var z = new Backbone.Collection(collection1);

console.log("same collection?", collection1==z.models);
console.log("same length?", collection1.length==z.length);
console.log("original model same size?", collection1.length==len)

var x = new Backbone.PageableCollection(collection2,{mode:'client',state:{pageSize:5}});

console.log("same collection 2?", collection2==x.models);
console.log("same length 2?", collection2.length==x.length);
console.log("original model same size 2?", collection2.length==len)
```

In this code, collection 2 should have a length of 50, but it does not, because it was modified directly by the constructor! The results should be the exact same as testing against Backbone.Collection.

With client side paging, it's pretty common that' I'm working with arrays that have lifetimes outside of my collections.  This is really making it difficult to use pagable.

**Comment by wyuenho** [comment]
Looks like the models array are still modified under non-server mode.
