### ISSUE TITLE
Pagination links are not being updated as "active" when clicked

### ISSUE THREAD

**Issue by jkowens** [backbone-paginator/backbone-pageable#116]
The first page and back arrows are always disabled and the current page is not properly styled. This issue can be seen in the client mode demo.

![image](https://f.cloud.github.com/assets/585943/1196664/8cfc503e-24b6-11e3-8b60-c455662e8a4c.png)

**Comment by wyuenho** [comment]
Try using pageable, paginator and backgrid master. This should have been fixed a few months ago. Let me know if it doesn't fix your problem.

**Comment by jkowens** [comment]
Ok thanks, pulling from master fixed the issue. I had downloaded the zipped 0.2.6 version from backgridjs.com.
