### ISSUE TITLE
Next row is added at the wrong postion in a pageable collection when deleting a row in the view

### ISSUE THREAD

**Issue by jurgenkalverboer** [backbone-paginator/backbone-pageable#118]
When I remove the highlighted row in the image below. 

![backgridremoverowbefore](https://f.cloud.github.com/assets/5629156/1350786/baae26ec-3712-11e3-9eec-5382b4bb8b67.png)

The next row in the collection should be added at the bottom of the pageable collection. However it is inserted one position too high.
![backgridremoverowafter](https://f.cloud.github.com/assets/5629156/1350739/b68df32c-3711-11e3-88fc-7586fe1d609a.png)

On the pageable collection I call the function remove with the corresponding model as its parameter. In backbone-pageable.js the collectionEventHandler is triggered by this action (with a "remove" event). Line 453 of this file will add a new row to the page collection:

if (nextModel = fullCol.at(pageEnd)) pageCol.push(nextModel);

This function will call the function inserRow immediatly on the pageable collection (in backgrid,js), this thus happens before the remove event will call the function removeRow. The index that is determined by the insertRow function is thus not correct:

 var index = collection.indexOf(model);

**Comment by excentris** [comment]
+1

**Comment by oosterholt** [comment]
+1

**Comment by ericbeijer** [comment]
+1

**Comment by KramerCJ** [comment]
+1

**Comment by WRidder** [comment]
+1

**Comment by Wietjerr** [comment]
+1

**Comment by beatle01** [comment]
+1

**Comment by wyuenho** [comment]
Let me know if b2a1aa1978972e2e7ded1d3fdc87cb96757b896e fixes this issue. I'll commit a test soon.

**Comment by wyuenho** [comment]
Actually forget that. It doesn't. Let me fix this in a moment.
