### ISSUE TITLE
Having backbone dependency from git crashes with version-specified backbone

### ISSUE THREAD

**Issue by Lacrymology** [backbone-paginator/backbone-pageable#119]
Having the backbone dependency defined as the git repo will always try to install the latest version. If I require backbone 1.1.0 and backbone releases a new version, this will not match, and will make node projects that want to use pageable fail, because pageable will patch the backbone at node_modules/backbone-pageable/node_modules/backbone and the app will try to use the backbone at node_modules/backbone

**Comment by wyuenho** [comment]
Fixed in 05af566

**Comment by Lacrymology** [comment]
great, thanks!

**Comment by wyuenho** [comment]
:+1:
