### ISSUE TITLE
backbone-pageable without AMD and CommonJs

### ISSUE THREAD

**Issue by skynet-tx** [backbone-paginator/backbone-pageable#124]
Good Day!
I have a suggestion.
People ask about it
https://github.com/wyuenho/backbone-pageable/issues/62
https://github.com/wyuenho/backbone-pageable/issues/58
All problem inside the module:
  // AMD
    else if (typeof define == "function" && define.amd) {
        define(["lo-dash", "Backbone"], factory);
    }
I'm using "lo-dash" library but in the module used "underscore" library.
 // AMD
    else if (typeof define == "function" && define.amd) {
        define(["lo-dash", "Backbone"], factory);
    }
It's wrong to change module. Fix this problem, please!

**Comment by wyuenho** [comment]
Both of the issues you referenced are unrelated to your problem, which is you are trying to use lodash instead of underscore. pageable has a hard dependency on underscore. There's no plan to change that and unlikely there will ever be as Backbone already has a hard dependency on underscore.

**Comment by BlessYAHU** [comment]
Lodash can be used instead of Underscore, so the dependency is on Underscore's api, not the library itself.  Please do not make this dependency on Backbone.Paginator, since you are merging that with this tool.

**Comment by BlessYAHU** [comment]
Just for the record adding a map to requirejs will get pageable to work with lodash:

  map: {
    '*': {
      'underscore': 'lodash'
    }
  },
