### ISSUE TITLE
state.totalRecords not correct set after removing rows

### ISSUE THREAD

**Issue by jurgenkalverboer** [backbone-paginator/backbone-pageable#129]
If you remove the last row of a page as follows

pageableCollection.fullCollection.remove(models)

state.totalRecords is updated correctly

However:

pageableCollection.remove(models)

will not update state.totalRecords correct, the value is one too high.

If you use backgrid-paginator in combination with backbone-pageable there will be an empty last page

**Comment by wyuenho** [comment]
Which version are u using?

**Comment by wyuenho** [comment]
and can i have a snapshot of ur states object?

**Comment by jurgenkalverboer** [comment]
Hmm, I can not reproduce it in your pageableTerritories example so I assume  it is fixed in a newer version

However when i go to the last page of the pageableTerritories example and execute the following command
pageableTerritories.remove(pageableTerritories.models)

the paginator will change to page16 but the page is not updated to page 16

**Comment by jurgenkalverboer** [comment]
I examined my first issue again and it is not fixed in your latest version (latest verstion backbone-pageable and latest version backgrid, backbone 1.1).

pageableCollection.fullCollection.remove(models)
-> if you removing models of the current page, the current page will not add new rows

pageableCollection.remove(models)
-> state.totalRecords is not updated correctly (if you remove rows on a page that is not the last page, the last page can become an empty page)

**Comment by jurgenkalverboer** [comment]
![state](https://f.cloud.github.com/assets/5629156/1712603/47f2235c-6178-11e3-8714-dcb962fad091.png)

**Comment by wyuenho** [comment]
Yeah it seems when a model is shifted from the fullCollection to the current page after deletion from the current page   causes totalRecords to be decremented and then immediately incremented again.
