### ISSUE TITLE
pageSize: 15, but only 1 in models

### ISSUE THREAD

**Issue by ChetHarrison** [backbone-paginator/backbone-pageable#130]
Jimmy,

I am a bit stumped. I copied and pasted the call to the db to verify that it is returning the expected JSON models. When I log the BB `models` attribute from my BB Pageable with the `pageSize: 15` in `infinite` mode I only see one model.

This looks like an ideal solution for my needs so I would love to get it working. Excellent work!!! I am working with Marionette.Backbone. I have an Entities module that handles all of the model/db transaction where I define the Pagable like so ...

```
        Entities.RecipePageableCollection = Backbone.PageableCollection.extend({
            url: "server/index.php/recipe",
            model: Entities.Recipe,
            mode: "infinite",
            state: {
                firstPage: 0,
                pageSize: 15,
                sortKey: "title",
                order: -1
            },
            queryParams: {
                offset: function () { return this.state.currentPage * this.state.pageSize; },
                currentPage: null,
                pageSize: "limit",
                totalPages: null,
                totalRecords: null,
                sortKey: "sort",
                order: "direction",
                directions: {
                    "-1": "asc",
                    "1": "desc"
                }
            }
        }); 

        var API = {
            getRecipePageableEntities: function(){
                return new Entities.RecipePageableCollection();
            }
       };
```

in my controller module I have the following code that listens for an event that calls that "getRecipePageableEntities" function in the Entities module via the request("recipe:pageable-entities"); call ...

```
var recipeCollection = NimbleChet.request("recipe:pageable-entities");
var recipesListView = new View.Recipes({
    collection: recipeCollection
});
recipeCollection.getFirstPage().done(function () {
   NimbleChet.mainRegion.show(recipesListView);
});
```

So when I log out the recipeCollection after the `.done()` I only see 1 model in the `models` attribute of the Pageable object. I was assuming I would see 15 models in the collection. I was hoping you could help me figure out what I am screwing up?

Thanks!!!

Chet

**Comment by wyuenho** [comment]
Well, pageSize != totalRecords, so if your server only returns 1 model from a request, you get 1 model. If might help if you log out the JSON response.

**Comment by ChetHarrison** [comment]
When I log out the JSON I get 15 records. There are about 220 records in the db.

**Comment by wyuenho** [comment]
Can you post the JSON response? The JSON response needs to be in a [special format](https://github.com/wyuenho/backbone-pageable#fetching-data-and-managing-states), are you returning that?

**Comment by ChetHarrison** [comment]
ah. so I need to modify my server to provide the state in the headers?

**Comment by wyuenho** [comment]
At the very least pageable needs to know how many records there will be in total

**Comment by wyuenho** [comment]
Just wrap this whole thing in another array, just like the doc said.

`[{"total_entries": 100}, [{"recipedId": 106, ...}, {...}, ...]]`

**Comment by ChetHarrison** [comment]
Ah. Thanks!

**Comment by ChetHarrison** [comment]
Jimmy,

The following code produces a `fullCollection` with 15 records and a `models` with 1 record. I was expecting `models` to contain 15 records and subsequent calls to the server, incrementing the `offset`, to append an additional 15 records to the `fullCollection`. Is that assumption correct or am I confused?  By the way, I did modify my server to return an array that wrapped an object containing the `totalRecords` and the records array discussed earlier. Thanks

```
    Entities.RecipePageableCollection = Backbone.PageableCollection.extend({
            url: "server/index.php/recipe",
            model: Entities.Recipe,
            mode: "infinite",
            state: {
                firstPage: 0,
                pageSize: 15,
                sortKey: "title",
                order: -1
            },
            queryParams: {
                offset: function () { return this.state.currentPage * this.state.pageSize; },
                currentPage: null,
                pageSize: "limit",
                totalPages: null,
                totalRecords: null,
                sortKey: "sort",
                order: "direction",
                directions: {
                    "-1": "asc",
                    "1": "desc"
                }
            }
        }); 
```

**Comment by ChetHarrison** [comment]
Jimmy,

I think I am making some progress looking at how you set up your infinite scroll example. I have a view rendering the `myPagableCollection.fullCollection` in a container view that has a reference to the `myPagableCollection` so on a scroll event I can call `myPagableCollection.getNextPage()`. However when I do I get a `RangeError: No link found for page 1`. So I must not understand the state object. Any advice?

Thanks,

Chet

**Comment by wyuenho** [comment]
You need to return a links object for infinte mode.

**Comment by wyuenho** [comment]
It might be clearer if you read the documents and/or source code for parseRecords and parseLinks.

**Comment by ChetHarrison** [comment]
ok thanks. I'll dig into the source.
