### ISSUE TITLE
client mode update collection when model is removed from server

### ISSUE THREAD

**Issue by solidstudio** [backbone-paginator/backbone-pageable#132]
Hi i'm having the following problem, when I remove a model from a collection using model.destroy the current pageable page doesn't correctly update so that it correctly renders the current page with the model removed and another model from the next page added in its place. To fix this I call this.collection.remove(view.model); before model.destroy has returned, but how can I avoid this?

Thanks

**Comment by wyuenho** [comment]
Can you produce a test case / jsfiddle?

**Comment by wyuenho** [comment]
Nvm. Found the bug.

**Comment by wyuenho** [comment]
Are you always removing from the front of the current page? Removing from the end of the current page seems fine.
