### ISSUE TITLE
What is the purpose of "getLastPage" in infinite mode?

### ISSUE THREAD

**Issue by AlexDomeshek** [backbone-paginator/backbone-pageable#135]
Hi!

I want to use infinite mode for case when the server side doesn't know what is the last page until it's actually reached.
So, how should I handle the "getLastPage" link in that case?

Thanks!

**Comment by wyuenho** [comment]
Don't return it. You can if you have it, it's not required. Only `next` is required.

https://github.com/backbone-paginator/backbone-pageable/blob/master/lib/backbone-pageable.js#L1009
