### ISSUE TITLE
Invalid Total Records Count for Infinite Scrolling

### ISSUE THREAD

**Issue by MGerrior** [backbone-paginator/backbone-pageable#136]
When using infinite scrolling it seems that the number of total records is always the number returned by the server plus the given page size. For example, given there are 100 records and a page size of 25, the pageable collection will state that there are 125 total records after fetching the first page.

I've created as JSFiddle ( http://jsfiddle.net/TDHfk/ ) to illustrate the problem that I am having. The fiddle uses the latest versions of Backbone and Backbone-Pageable. Since the API I am using requires authentication, I have used Sinon.js to create a fake server and provide a response to the JS fiddle. As you can see in the example, the state of the collection indicates that there are 5 total records, despite the fact that the server indicated there are only three total entries.

**Comment by wyuenho** [comment]
Looks like adding to the full collection inside the success callback inside #fetch after parsing has already been done has caused some state inconsistencies.

https://github.com/backbone-paginator/backbone-pageable/blob/master/lib/backbone-pageable.js#L1216

**Comment by wyuenho** [comment]
@MGerrior , I'm curious, why do you need to send down the `totalRecords` from the server and why do you need the authoritative totalRecords to be that? Infinite paging mode doesn't actually fetch the next page unless there's a `next` entry in the internal `links` hash.

**Comment by wyuenho** [comment]
@MGerrior See this [comment](https://github.com/backbone-paginator/backbone-pageable/issues/139#issuecomment-32708645).

I'm going to revert the change made for #139 and make explicit in the docs that you shouldn't override `parseState` under infinite mode, you just don't need it.

**Comment by MGerrior** [comment]
@wyuenho I'm passing down the number of total records from the server so it can be displayed to the user. Surely I could just update the count on the page when parsing from the server, or store the state somewhere else, however I wanted the collection to maintain the state from the server.

**Comment by wyuenho** [comment]
I've updated the README to clarify this. 

https://github.com/backbone-paginator/backbone-pageable/commit/7f799b2107cf1b573bf51c309ba1f381ae29f97f

**Comment by wyuenho** [comment]
@MGerrior In general, the `totalRecords` on the server is meaningful to the user only if you are in a single user environment. Between page fetches on one client, the server could have easily added multiple pages of records. Thus `totalRecords` is only useful to keep track of the local state. Moreover, if `totalRecords`, which is a bounded quantity, becomes meaningful under infinite mode, infinite paging isn't really infinite paging would it :)?
