### ISSUE TITLE
url for demo infinite-paging doesnt work

### ISSUE THREAD

**Issue by oak-tree** [backbone-paginator/backbone-pageable#137]
https://api.github.com/repos/twitter/bootstrap/issues?

returns:
{
  "message": "Not Found",
  "documentation_url": "http://developer.github.com/v3"
}

**Comment by wyuenho** [comment]
The demo works, but your URL doesn't. The URL should be https://api.github.com/repos/twbs/bootstrap/issues

**Comment by oak-tree** [comment]
thanks for quick reply. but i still get error on http://backbone-paginator.github.io/backbone.paginator/examples/infinite-paging/index.html

**Comment by wyuenho** [comment]
You've filed this issue on the wrong repo man :) It's the other repo's demo that's broken :)

**Comment by oak-tree** [comment]
will do thanks :)
