### ISSUE TITLE
Syntax to bind pager template to pager methods

### ISSUE THREAD

**Issue by moniuch** [backbone-paginator/backbone-pageable#143]
This is my first day with Pageable, a very very encouraging experience! Maybe it's too early to submit an idea, but I feel like contributing in any possible way to the plugin.

So, unless I'm missing something, could we have an easier way to bind pager ui to the plugin? For instance I would like to be able to code the following way:

``` javascript
MyColl = Backbone.PageableCollection.extend({
        pagerTemplate: '#tpl-pager', // or a function

        pagerEvents: {
          'nextPage' : 'myNextPageHandler',
          'lastPage' : function(e, state){

          }
        },

        function myNextPageHandler(e, state){
          // event, state
        }
})
```

As per `pagerTemplate`: I would like to be able to use the pager twice - at the top and bottom of a table.

I know it looks like misplacing MVC stuff around, but please take it just as an idea of a syntax.

I hope I will be able to contribute with code some day. Thank you.

**Comment by wyuenho** [comment]
Pageable has and will always be the model layer. UI stuff is not the concern for this project. You can take a look at wyuenho/backgrid-paginator to see how a paginator UI could be implemented. As a bonus, backgrid-paginator can totally be used outside of backgrid, you just have to edit out 4 lines of code.
