### ISSUE TITLE
Little concern about getLastPage() in server mode

### ISSUE THREAD

**Issue by billychan** [backbone-paginator/backbone-pageable#151]
I have a little question about `getLastPage()` in server mode.

Imagine a case to show paged comments on an article sorted by time ASC, and I want to show the last page at first.

Since the client side has no idea how many comments are there in server, what I need to do is to feed the collection with comments number at initialization, and then reply on Pageable to calculate last page.

```
initialize: (totalComments)->
  @state.totalRecords = totalComments

state:
  perPage: 10

# then
commentsCollection.getLastPage()
```

There are several concerns:
1. Extra initialization code and dependency on `totalComments` provided by another model.
2. The number would be sometimes unreliable. Assume an edge case when Article shows 30 comments, but when loading comments, there may be more comments already added and then the last page is incorrect.
3. If there is no such number provided, say I want to show same style on Article but not Comment, I have no place to get that number except an extra request.

I think, in server mode, is it necessary to not rely on client side to calculate last page but let server do it? Say sending a `last_page=true` parameter?

**Comment by wyuenho** [comment]
You can send down a new set of state from the server. You only need to provide a `totalRecords` if you are bootstrapping. If you fetch after initialization you can just use the state from the server. The state can contain anything you want to update.

https://github.com/backbone-paginator/backbone-pageable#adapting-to-a-server-api

**Comment by billychan** [comment]
@wyuenho Thanks for your super quick reply. I got your idea, "bootstrapping", that makes sense. Thank you.
