### ISSUE TITLE
infinite collection / fullcollection is confusing

### ISSUE THREAD

**Issue by gaisho** [backbone-paginator/backbone-pageable#155]
Please be patient with me.  I'm trying to setup continuous (infinite) pagination so I set the mode to "infinite"

Strange part is that my Marionette.CompositeView is rendering only 1 item.  I checked and indeed there is only 1 model in the top level of the collection, however in the fullCollection there's the "full collection" of models.

How do I display all my entire collections and bind that to marionette because under normal circumstances, I would simply set a normal collection and everything would work.

**Comment by wyuenho** [comment]
Instead of setting `collection: pageableCollection`, set `collection:pageableCollection.fullCollection` into your CompositeView when calling the constructor. Simple as that.

**Comment by gaisho** [comment]
Thanks for the speedy response.

It seems when I get the next page, the collection removes the previous page.  I say this because the pageableCollection and fullCollection have the same models in them even after successfully fetching the next page.

Is there something I could be doing wrong?
I use collection.getNextPage() and I manually set the parseLInks to increment the "page" to fetch new data.

**Comment by wyuenho** [comment]
Can you post some code?

**Comment by gaisho** [comment]
Thanks for you help.  Please note that I've taken snippets of what I think is relevant.  Some variables may be instantiated elsewhere.

```
// MODELS & COLLECTIONS
Post = Backbone.Model.extend({
    defaults : {        
        thumbnail : "",
        thumbnail_images : ""
    }
});

Posts = Backbone.PageableCollection.extend({
    model : Post,
    url :aqs.api_url + "/get_posts",
    mode : "infinite",
    queryParams : {
        pageSize : "count",
        currentPage : "page",
        totalPages : null,
        totalRecords : null
    },

    state :{
        pageSize: 12,
        firstPage: 1
    },

    parseRecords : function(resp){      
        this.state.totalRecords = resp.count_total;
        return resp.posts
    },

    parseLinks : function(resp,xhr){
        if(resp.count < resp.count_total){

            resp.query.page ++;
            var next_url =  aqs.api_url + "get_posts/?" + serialize(resp.query);
            var first_url =  aqs.api_url + "get_posts/?" + serialize(resp.query);

            return {
                "next" : next_url,
                "first" : first_url
            }
        }
        else{

            return false;
        }

    }

});

EntryView = Marionette.ItemView.extend({
    template :"#tmp-entry",
    className :"col-md-3 col-sm-4 col-xs-12 excerpt",   

    templateHelpers:  {
        has_thumbnail : function(){
            if(this.thumbnail){
                return "has-thumbnail";
            }
        },

        get_thumbnail : function(){
            if(this.thumbnail){
                var thumb = this.thumbnail_images['writings-carousel-thumbnail'];
                return "<a href='"+this.url+"'><img src='"+thumb.url+"'/></a>";
            }
        }
    },

    onRender: function(){
        var t = this.model.get("tags");
        if(t.length){
            var tags = new Tags({
                collection : new Backbone.Collection(t)
            })

            tags.render();
            this.$el.find(".tags").append( tags.$el.html() );
        }
    }
})

EntriesView = Marionette.CompositeView.extend({

    template : "#tmp-entries",

    className : "row excerpts",

    itemViewContainer : "#entries-body",

    itemView :EntryView,

    templateHelpers : {

        get_title : function(){
            return this.title;
        }
    },

    collectionEvents : {

    },

    events : {
        "click #load_more_button" : "ev_load_more"
    },  

    ev_load_more : function(){
        this.trigger("loadmore");
    },

    evCollectionReset : function(){

        this.render();
    },

    get_summary : function(){
        var offset = (this.collection.pageableCollection.state.currentPage - 1) * this.collection.length + 1 ;

        if(this.collection && this.collection.length){          
            return "showing " + offset + "-" + this.collection.length * this.collection.pageableCollection.state.currentPage + " of " + this.collection.pageableCollection.state.totalRecords + " entries"; 
        }
        else{
            return "no entries";
        }   
    },

    onRender : function(){
        this.$el.find(".entries-title").html( this.title );
        this.$el.find(".entries-summary").html( this.get_summary() ) ;
        this.$el.removeClass("loading");
    }
});

jQuery(document).ready(function() {
// get recent posts
    var posts = new Posts();    
    posts.getFirstPage().done(function(){

        jQuery(window).trigger("reset");
        regions.entries.show(entriesView);

    });

var entriesView = new EntriesView({
        collection : posts.fullCollection
    });

entriesView.on("loadmore", function(){
        posts.getNextPage();
    })
});

```

**Comment by wyuenho** [comment]
What does the response look like?

**Comment by gaisho** [comment]
I've attached results for page 1 and page 2.  Please let me know if you need the actual data.

![capture](https://cloud.githubusercontent.com/assets/4890364/2626018/9cd6e4da-bdb6-11e3-9fd3-0632d59ad084.PNG)
![capture__2](https://cloud.githubusercontent.com/assets/4890364/2626019/9ce53e86-bdb6-11e3-9cdc-3148faba56f6.PNG)

**Comment by wyuenho** [comment]
First of all, you are manipulating the state from inside `parseRecords`, the contract of `parseRecords` is that it should be side-effect free. It is also unnecessary to set a total for infinite paging. The total is the current total number of records fetched that's on the client side. I suspect this is what's confusing the state calculation. As I've said in the README, in general you should never directly manipulate the state yourself.

Second of all, the count is the page size, why would it ever be >= count_total? This is irrelevant to the discussion but I just want to point that out.

I'm also not sure why you can't just send down the links directly from the server. The numeric values inside `query` are also all strings, they should be numbers. This is also irrelevant but they just bother me.

**Comment by gaisho** [comment]
I removed the  `this.state.totalRecords = resp.count_total` but still.  the new records are replacing the existing records in the collection;  it's not appending the fullCollection.

The reason I added count_total to the state is more for aesthetics.  I wanted to show in the header (in the View) how many records are available in total just to give context to the user.   You are right about the links though.

Anyway, maybe there's a bug in the collection, but I'll also look.  Maybe there's something I'm not doing right somewhere.

**Comment by wyuenho** [comment]
I have no idea then. Doesn't look like there's another else wrong with the collection code. Just curious, which version of pageable and backbone are you using?

**Comment by gaisho** [comment]
backbone version 1 (am using the one shipping with wordpress)
pageable version 1.4.5

**Comment by wyuenho** [comment]
pageable is incompatible with backbone 1.0. It broke a number of things. Use backbone >= 1.1.0

**Comment by gaisho** [comment]
aahh.. thanks.  let me give it a shot.

**Comment by gaisho** [comment]
Voila!!  it works!!
Thank you very much for your help.

**Comment by tilwinjoy** [comment]
4 years later I'm facing the same issue. Helpful discussion :)
