### ISSUE TITLE
Relationship between parseLinks and queryParams in infinite mode

### ISSUE THREAD

**Issue by gaisho** [backbone-paginator/backbone-pageable#156]
I'm using infinite mode.  My server is returning pagination link as per the documentation.  The returned links also contain additional query string variables that are not defined in queryParams. i.e. cat=x

It seems when I invoke `collection.getNextPage()`, the collection generations the url using queryParams instead of using the "next" url that I set in parseLinks.

Maybe I don't quite understand the relationship between parseLinks and queryParams.   Please clarify.

The links hash returned by my server looks something like this:
![image](https://cloud.githubusercontent.com/assets/4890364/2628417/f6ddac6a-be25-11e3-8679-e268870be745.png)

**Comment by wyuenho** [comment]
queryParams generates the URL on the first fetch, as long as there are next URLs under infinite mode, all the subsequent requests should be made by the next URLs coming from the server.
