### ISSUE TITLE
Uncaught RangeError: `currentPage` must be firstPage <= currentPage >= totalPages if 0-based. Got 7.

### ISSUE THREAD

**Issue by hoangpx** [backbone-paginator/backbone-pageable#158]
My total_pages = 1 and my total_entries = 63. I'm displaying page with 100 items and change page size to 10. Then it throw this error.
This is my configuration : 
       state: {
            pageSize: 20,
            firstPage: 0

```
    },
    queryParams: {
        currentPage: "offset",
        pageSize: "limit",
        sortKey: "sortBy",
        totalRecords: "total_entries",
        order: "sortOrder"
    },
```

**Comment by wyuenho** [comment]
If you are displaying a page with 100 items then why do you have a pageSize of 20? How did you change the page size?

**Comment by hoangpx** [comment]
My initial page size is 20. I have options to choose page size [10, 20 ,50, 100]. First I changed page size to 100. It's ok. After that I changed to 10. It throw that error.
This is how I change page size : 
this.collection.setPageSize(pageSize);
Thanks for your quick response.

**Comment by wyuenho** [comment]
I can't reproduce it from the backgrid examples. Which version of backbone and pageable are you using?

**Comment by hoangpx** [comment]
Backbone.js 1.0.0 and backbone-pageable 1.4.5

**Comment by wyuenho** [comment]
Can you please upgrade to backbone >= 1.1.0 and try again please? pageable doesn't work with 1.0.0.

**Comment by hoangpx** [comment]
OK, I changed bb to 1.1.2 and it's still happen.

**Comment by hoangpx** [comment]
This is state before I changed page size 
![screen shot 2014-04-09 at 9 04 35 pm](https://cloud.githubusercontent.com/assets/1779511/2656263/e70f3206-bfef-11e3-913f-2a59d97bab93.png)

**Comment by wyuenho** [comment]
Ah ok. Looks like this only happens when firstPage is 0 and when you are shrinking the page size

**Comment by wyuenho** [comment]
For now you can use setPageSize(10, {first: true}) to get around this. This is most likely what you'll want to do anyway.

**Comment by hoangpx** [comment]
It worked. Thanks a million.
