### ISSUE TITLE
Problematic line in combination with uglifier...

### ISSUE THREAD

**Issue by SachaMPS** [backbone-paginator/backbone-pageable#160]
Hi there,
i had some problems since today building our project. It stopped during the "uglify" procedure. At the end i figured out that removing console.log statements corrupted the following type of lines from the actual source:

https://github.com/backbone-paginator/backbone-pageable/blob/master/lib/backbone-pageable.js#L756

The result was something like this, which breaks the code (see the && statement followed by nothing before the return):

```
  hasPrevious: function () {
        var msg = "hasPrevious has been deprecated, use hasPreviousPage instead";
        typeof console != 'undefined' && console.warn && 

        return this.hasPreviousPage();
      },
```

I could imagine that this might be a problem for several people which uglify their code...

Kind regards and thanks for your work,
Sacha

**Comment by wyuenho** [comment]
Uglify's default is to set drop_console to false, did you set it to true ?

**Comment by wyuenho** [comment]
@SachaMPS do you still have this problem after resetting the `drop_console` to false?

**Comment by SachaMPS** [comment]
@wyuenho 

Sorry for the late response.. I think i made a  little mistake in my assumption. After inspecting the build task again in that specific project i found that it didnt happen because of uglify. (Uglify has a remove_debugger option but this wouldnt affect console.log(...). It seemed to happen because of this package: https://www.npmjs.org/package/grunt-remove-logging. As stated in the docs of this grunt package there's already an option which wouldnt break the code in that specific case. So i think thats not an direct issue of your code. Sorry for that inconvenience...
