### ISSUE TITLE
Setting order to null in queryParams sends null=desc or null=asc to server

### ISSUE THREAD

**Issue by yogiHulk** [backbone-paginator/backbone-pageable#161]
queryParams: {
            order: null
},

should not send order to backend. Instead, it sends null=asc to backend

Also, if the server requests the same parameter name as one of the states, but the value needed is in a different format, there is no way to do that.

something like

queryParams: {
            order: function() { return .....}
},
 makes the api think the value is the name of the parameter

**Comment by wyuenho** [comment]
> should not send order to backend. Instead, it sends null=asc to backend

`order` is only sent as a request parameter if a [sortKey](https://github.com/backbone-paginator/backbone-pageable/blob/master/lib/backbone-pageable.js#L1170) was defined. Why would you want to fetch a sorted set of results from the server without telling the server which key it should sort on?

> Also, if the server requests the same parameter name as one of the states, but the value needed is in a different format, there is no way to do that.

There's a method called `parseState` that translates server state back to the state format used in pageable.

https://github.com/backbone-paginator/backbone-pageable#fetching-data-and-managing-states

**Comment by yogiHulk** [comment]
Hi @wyuenho , thank you for the reply. What I'm trying to do is to call backend with a parameter 
sort=-name which is equal to sort_by=name, order=desc 
sort=name which is equal to sort_by=name, order=asc

The following code sends these parameters(in a test I did) to the backend
limit=<number>&null=desc&offset=0&sort=-name&filter=Filter  
so everything is correct other than the 'null=desc' part. How do I remove that? If I want to change my custom parameter 'sort' to be called 'order', a name which is already reserved by the library, is there a way to do that?

```
define([

    // libraries
    'moment', 'backbone.pageable'

], function (

    // libraries
    moment, PageableCollection

    ) {

    return PageableCollection.extend({

        //todo add properties/default section

        mode: 'server',
        url: '/api',
        //current state of collection
        state: {
            firstPage: 0,
            currentPage: 0,
            pageSize: 10,
            totalRecords: 0,
            order: -1,
            filterObj: null
        },

        // parameters which server accepts. 
        // existing state properties map to new property name
        // new properties (properties not present in state object) are sent as is with the value provided
        // null means that the state parameter will not be sent to the server
        queryParams: {
            offset: function() { return this.getServerOffsetParam(); },
            sort:   function() { return this.getServerSortParam(); },
            filter: function() { return this.getFormattedFilter(); },
            pageSize: "limit",

            currentPage: null,
            totalPages: null,
            totalRecords: null,
            sortKey: null,
            directions: null,
            order: null
        },

        parseState: function (response) {
            PageableCollection.prototype.parseState.call(this, response);
            this.state.totalRecords = response.totalCount;
        },

        fetch: function (options) {
            options = options || {};
            options = _.extend(options, {type: 'POST'});
            PageableCollection.prototype.fetch.call(this, options);
        },

        getServerOffsetParam: function () {
            return this.state.currentPage * this.state.pageSize;
        },

        getServerSortParam: function () {
            return (this.state.order > 0 ? "-" : "") + this.state.sortKey;
        },

        getFormattedFilter: function () {
            return this.getFilter() && typeof this.getFilter().toJSON === 'function' ?
                this.getFilter().toJSON() :
                this.getFilter();
        },

        getFilter: function () { return this.state.filterObj; },

        setFilter: function (filter) { this.state.filterObj = filter; },

        getTotalCount: function () { return this.state.totalRecords;}
    });

});
```

**Comment by wyuenho** [comment]
Fixed in https://github.com/backbone-paginator/backbone.paginator/pull/227
