### ISSUE TITLE
Removing all items on a page does not change the page

### ISSUE THREAD

**Issue by martindrapeau** [backbone-paginator/backbone-pageable#162]
So I have a backgrid with 2 pages. The second page has 2 items. I remove them and then the paginator updates, but the backgrid is left with an empty page. I would expect the backgrid to fall back to the previous page.

To test, use this fiddle, go to the second page and remove all items.
http://jsfiddle.net/martindrapeau/77BLZ/3/

**Comment by wyuenho** [comment]
See backbone-paginator/backbone.paginator#232
