### ISSUE TITLE
Error in fetch if collection's url is a method

### ISSUE THREAD

**Issue by ami7ava** [backbone-paginator/backbone-pageable#30]
Fetching a collection throws error if the collection'l url is a method, not property.

Here is a [jsfiddle](http://jsfiddle.net/n6JDJ/) to demonstrate the issue.

**Comment by wyuenho** [comment]
Care to provide a PR? This one should be easy.

**Comment by ami7ava** [comment]
@wyuenho I hope the PR is good. Just not sure about the test I've added. As I am not quite familiar with qunit, so copied the previous test and changed the url to a method to check if it passes.
