### ISSUE TITLE
AMD+sorting issue: 'Uncaught TypeError: Expecting a function in instanceof check'

### ISSUE THREAD

**Issue by abirmingham** [backbone-paginator/backbone-pageable#33]
If backbone-pageable.js is loaded via AMD, then PageableCollection is not set on the Backbone object is not defined globally. However, Backbone.PageableCollection in backgrid.js:1526, in sort(). This causes an exception when the user attempts to sort (e.g. clicks a column header): 'Uncaught TypeError: Expecting a function in instanceof check, but got [object Object]'.

I was able to work around this issue by adding backgrid as a shim with an init method in my require.js config(). See below for that config.

Is this user error? Did I do it wrong? I think I'd expect Backgrid to specify PageableCollection as a dependency and reference that as a local. Thanks for the great library. :)

```
require.config({
    baseUrl: '/js/app/',
    paths: {
        // Major libraries
        underscore: '/js/vendor/underscore/underscore',
        backbone:   '/js/vendor/backbone/backbone',
        mustache:   '/js/vendor/mustache/mustache',
        backgrid:   '/js/vendor/backgrid/backgrid',

        // Backbone plugins
        'backbone-pageable': '/js/vendor/backbone-pageable/backbone-pageable',
    },
    shim: {
        backgrid: {
            exports: "Backgrid",
            deps: ['underscore', 'backbone', 'backbone-pageable'],
            init: function(_, Backbone, PageableCollection) {
                this.Backbone.PageableCollection = PageableCollection;
            }
        }
    }
});
```

**Comment by wyuenho** [comment]
Check out the Backgrid.js 0.2.0-wip branch and see if you still have this problem. Help me close this if it's fixed.

**Comment by abirmingham** [comment]
Thanks wyuenho. Indeed all is well on 0.2.0-wip. I do still need the shim in order to access Backgrid as an exportable AMD module, but the the init() function is no longer required. Sort works without error. Also apologies, should have created this issue on backgrid, not backbone-pageable. Closing.
