### ISSUE TITLE
Infinite mode and pre-loaded collection

### ISSUE THREAD

**Issue by TimNZ** [backbone-paginator/backbone-pageable#35]
I am preloading the collection with infinite mode.

Paging through works fine, but I have to manually add a new links entry for the 'next' page otherwise  system returns false for hasNext() when it has reached the end of the collection.

E.g.
pageSize = 10
initial collection size = 20
links.length = 2
hasNext() = false when on page 2

Adding a links[3] = 'http...' after creating PageableCollection allows infinite to continue to work .. infinitely.

**Comment by wyuenho** [comment]
Yeah I'm really not sure what to do here. The thing is that the collection just wouldn't know whether your server has any more data or what the "next" URL would look like if you are not bootstrapping the whole thing like you do under client mode. It doesn't even know if you are bootstrapping the whole thing. You can do `col.getLastPage({fetch: true});` to force a fetch if you are sure you have more stuff or just want to double check.

Any suggestions to improve this is welcomed.

**Comment by TimNZ** [comment]
I was thinking that as well, no obvious default value.  Will have a think and update soon, wasted a lot of time yesterday and I have a deadline..
