### ISSUE TITLE
[Feature Request] Caching

### ISSUE THREAD

**Issue by jbraithwaite** [backbone-paginator/backbone-pageable#40]
In server mode, could there be caching based on the queryParams? I.E. the same set of query params will only go to the server once.

**Comment by wyuenho** [comment]
I'm not sure what you mean, do you care to elaborate?

**Comment by jbraithwaite** [comment]
I'm using pageable in conjunction with Backgrid-paginator and every time there is a change to the sort order there is a new request to the server. For example, if I were to change the sort order of email from `asc` to `desc` to `asc`, the requests would look like this:

http://example.com/api/users?page=1&per_page=4&sort_by=email&order=asc
http://example.com/api/users?page=1&per_page=4&sort_by=email&order=desc
http://example.com/api/users?page=1&per_page=4&sort_by=email&order=asc

If the collection was cached (based on the query parameters) there would only be two HTTP requests regardless of how many times the user clicked on the sort order of email column.

**Comment by wyuenho** [comment]
Try [client mode](https://github.com/wyuenho/backbone-pageable#client-mode). Sorting will be done entirely on the client side without having to make a new request every time, but you can still force a fetch if you need to.

FYI, you should probably check out the Backgrid 0.2.0-wip branch and run a build yourself. There are lots of bug fixes there.

Let me know if this solves your problem, if it does then please help me close this issue.

**Comment by jbraithwaite** [comment]
Thank you Jimmy for your quick responses! After reviewing the documentation for client mode, I think it will be a perfect fit. You're doing amazing work, let me know if you setup a [donation link](https://www.gittip.com/on/github/wyuenho/)
