### ISSUE TITLE
[Feature Request] Query by URL path

### ISSUE THREAD

**Issue by robcolburn** [backbone-paginator/backbone-pageable#45]
Provide an _option_, _method_, or _example_ for connecting API's that use URL paths rather than query strings.

Example:
http://some-api/posts/2/
http://some-api/sortedBy/alpha/page/2/perPage/10/

Backstory:
I've been finishing up some customizations to Backbone.Paginator, when I stumbled across your library.  I really like it, though it's a bit rigid about the URL structure and response structure of the API you're connecting with.  I think it can be improved by allowing more flexibility there.

**Comment by wyuenho** [comment]
Querying by URL path makes no sense. It's not RESTful and supporting this scheme will greatly bulk up the code base. AFAIK, not even Backbone.Paginator supports this. If you need this functionality to support some legacy apps, you are on your own.

**Comment by robcolburn** [comment]
Fair enough, it turns out my purposes are going a bit tangent to some other concepts in Pageable or Paginator.  Hoping I can release something this/next week.
