### ISSUE TITLE
[Feature Request] Example of custom parse method

### ISSUE THREAD

**Issue by robcolburn** [backbone-paginator/backbone-pageable#46]
Provide an _example_ for connecting API's that use complex response structures.

Example:

``` json
{
    "totalPages": 100,
    "page": 3,
    "results": [
        {"name": "jane", "age": 35},
        {"name": "john", "age": 22},
    ]
}
```

The `parse` method supplied modifies `this.state`, but it's not immediately obvious how someone extending the class should use it.

This looks like it would be a proper method, but I'm not sure.

``` js
parse: function (resp) {
    if (resp && resp.results) {
        return new TypeError("The incoming data format did not match the format we expected.");
    }
    this.state = _checkState(_.defaults({
        totalRecords: resp.totalPages * this.state.pageSize
    }, this.state));
   return resp.results;
}
```

Backstory:
I've been finishing up some customizations to Backbone.Paginator, when I stumbled across your library.  I really like it, though it's a bit rigid about the URL structure and response structure of the API you're connecting with.  I think it can be improved by allowing more flexibility there.

**Comment by wyuenho** [comment]
Judging from your response structure, the correct `parse` method should be something like this:

``` javascript
parse: function (resp) {

  // make sure the response structure is acceptable
  if (!_.isObject(resp) || !resp.results) {
    return new TypeError("The incoming data format did not match the format we expected.");
  }

  // update pageable states by translating server states to pageable states.
  var queryParams = this.queryParams;
  var newState = _.clone(this.state);
  var serverState = resp;

  _.each(_.pairs(_.omit(queryParams, "directions")), function (kvp) {
    var k = kvp[0], v = kvp[1];
    newState[k] = serverState[v];
  });

  if (serverState.order) {
    newState.order = _.invert(queryParams.directions)[serverState.order] * 1;
  }

  // make sure the state is sane
  this.state = this._checkState(newState);

  return resp.results;
}
```

I suppose the really confusing part is when to call `_checkState` and how to translate server state back to pageable state. Maybe extracting the translation into a helper method will make customizing `parse` easier. A few words in the README on what a `parse` method is expected to do at the beginning and end would be good too.

Care to submit a PR?

**Comment by robcolburn** [comment]
There's a lot of logic there I don't quite understand.  I'm going write my own Paginator, I'm hoping to release this/week next week.  Pageable seems more focused on backends with a degree of control.

**Comment by wyuenho** [comment]
What "magic" you don't understand? It's pretty well documented and highly flexible and customizable. Most of the time it just works. Let me know so I can improve it.
