### ISSUE TITLE
repo is "un-clonable" on Windows

### ISSUE THREAD

**Issue by bryanbuchs** [backbone-paginator/backbone-pageable#47]
The "Fix #1 playable demos" commit added JSON files with query parameters as part of the filename (`territories.json?page=2&per_page=15`). While I'm able to clone the repo successfully on my macbook, it fails on my Windows 7 machine. I've tried using the command line and two different GUIs. All give me the same error message:

`error: unable to create file examples/json/territories.json?page=1&per_page=15
 (Invalid argument)`

AFAIK, a `?` is an illegal character for a filename in Windows. 

The rest of the files are present, but the repo is stuck in a dirty state due to the missing files. Normally not a big problem as it's just the sample data missing, but it does throw off the package manager I'm using (bower).

**Comment by wyuenho** [comment]
What is your solution to this Windows file system idiocy?

**Comment by bryanbuchs** [comment]
Well, it looks to me like you're trying to simulate calls to a server-based API using flat files? I would guess the purpose of that would be so the demo can be run without any server backend, correct? 

_My_ solution would be to pump out a quick PHP script to serve up the files. So the naming scheme for the JSON would be `territories-1.json`, `territories-2.json`, etc. And the PHP script would look at the `page` parameter and return the corresponding JSON file. 

https://gist.github.com/bryanbuchs/5006818

I say PHP because (a) that's what I'm familiar with and (b) it's relatively ubiquitous.

**Comment by wyuenho** [comment]
Any solution that just uses the file system? I don't want to fire up a web server.

**Comment by monzou** [comment]
Hi, @wyuenho 

I got a same problem on Windows for installing backbone-pageable via bower.
I know you don't want to change for this Windows file system idiocy (I would think so too if I were you), but this is necessary for supporting Windows (+ bower) users.

Could you change the filenames for supporting Windows (or PR) ?
(ex. territories.json_page=10&per_page=15)

**Comment by wyuenho** [comment]
Not that I don't want to change, but I don't have a windows machine to test this with. Pull requests welcome. You should be able to fix this without requiring a server. All you need is to encode/decode the URI components.

**Comment by monzou** [comment]
encode/decode URI component ?

A simple solution for example is to change emulated API @ server.html to not use query parameters like `json/territories/1/data.json/15` or `json/territories.json_page=1&per_page=15`.
Of course this works on Windows, but I guess you don't want to do ?

**Comment by bryanbuchs** [comment]
@wyuenho: " All you need is to encode/decode the URI components." 

No, that's not the issue. The file system won't allow a filename that uses reserved characters. Using reserved characters in a filename is generally considered bad practice for cross-platform development. I understand what you're trying to do -- demonstrate the app without the need for a server -- but you're doing it at the expense of a very large chunk of your audience. 

If you are dead set on a demo without a server, why not use bootstrap the data and use the "client" mode?

**Comment by bryanbuchs** [comment]
Pull request sent with fix for server mode.
