### ISSUE TITLE
Potential bug with parseRecords, parse (maybe)

### ISSUE THREAD

**Issue by ileto** [backbone-paginator/backbone-pageable#54]
Tonight I looked closely with your source. I configed a  parseRecords in my Collection. When finished fetching data, FullCollection gets to call the parseRecords which works fine. But then after models slice, when you trying to use the paged models to reset the PageCollection, the parseRecords called again with the plat data structure, which will cause the issue.
E.g.
Server Response
{ total_number:120, users:[0...120]}
parseRecords: (resp)->
    resp.users

**Comment by wyuenho** [comment]
I'm not sure what you mean. `fullCollection` is never used to perform a `fetch` and `reset` doesn't trigger a call to `parse`. Can you provide a failing example?

**Comment by ileto** [comment]
I debugged very deep to find that,, so it's pretty hard to provide an example. Kind of remember:
###collectionEventHandler
if (event == "reset" || collection == fullCol) {
            if (!(state.totalRecords = fullCol.models.length)) {
              state.totalRecords = null;
              state.totalPages = null;
              state.lastPage = state.currentPage = state.firstPage;
            }
            pageCol.state = pageCol._checkState(state);
            if (collection == pageCol) fullCol.trigger(event, fullCol, options);
            resetQuickly(pageCol, fullCol.models.slice(pageStart, pageEnd),
                         options);
}

### after the fullCol.trigger 'reset' -> pageCol got resetQuickly with the sliced models.

function resetQuickly () {
      collection.reset.apply(collection, resetArgs);

### pageCol.reset applied....and looks like the Backbone prototype reset got executed which will do the parse again.

### MY SOURCE

```
User = Bac.Model.extend
    initialize: ->

Users = Bac.PageableCollection.extend
    model: User
    url: 'api/v1/relationships/list'
    mode: 'client'

    setType: (type)->
        this.queryParams.type = type
        this.queryParams.cursor = 0

    parseRecords: (resp)->
        # hot fix for pagable potential bug: pageColl parseRecords again with results from fullColl parseRecords
        if resp.users then resp.users else resp
```

### SERVER RESP

{
total_number: 120,
users: [{},{},{}....]
}

HAHA, I just meet your plugin hours ago, so dont laugh me at the queryParams.type or cursor thing.
BTW, if any way to add extra queryParams more easily, if i don't want to change the build queryParams?

**Comment by wyuenho** [comment]
`parse` is only called if `options.parse` is truthy when you call `reset`. It's not normally called. The canonical way to add new `queryParams` parameters is to either provide it during override, initialization, or supply them to `fetch`. There are many ways to do it.
