### ISSUE TITLE
Save collection.fetch data argument

### ISSUE THREAD

**Issue by Integral** [backbone-paginator/backbone-pageable#57]
Hello!

I use `server` mode.
I'm trying to fetch my collection with some data argument (for querying db - `this.collection.fetch({data:{query:query}});`), so I send GET request to server:
`/api/mycollection?query=myquery&page=1&per_page=3&total_pages=2&total_entries=60&sort_by=lastName&order=asc`
But when I press next on pager I sent just `/api/mycollection?page=1&per_page=3&total_pages=2&total_entries=60&sort_by=lastName&order=asc`, so I'm losing my query when I navigate through pager.

**Comment by wyuenho** [comment]
Fetching with jQuery data is meant to be used as a one-off query. If you want your query parameters to persist across pagination, you can supply extra parameters in `queryParams`.

https://github.com/wyuenho/backbone-pageable#id18
https://github.com/wyuenho/backbone-pageable#id24

**Comment by Integral** [comment]
Don't really understand how do it.
I understand that I need to pass `query` value inside `queryParams` object. But how could I receive data param inside collection definition?

**Comment by wyuenho** [comment]
If you look at the FBComment example, you can set anything you want inside `queryParams` and they will be in the query string when you fetch a page. The values of your `queryParams` keys can be functions too, so they need not be static.

``` javascript
...
queryParams: {
    "query": function () {
        return someOtherFunctionThatGivesYouTheQueryString();
    }
}
```

https://github.com/wyuenho/backbone-pageable#adapting-to-a-server-api
https://github.com/wyuenho/backbone-pageable#infinite-mode

**Comment by Integral** [comment]
Yes! I saw this! But don't understand how could I receive data param from fetch here.

**Comment by wyuenho** [comment]
What do you mean by "receive data param from fetch" ?

**Comment by Integral** [comment]
I make query from my view:
`this.collection.fetch({data:{query:myquery}});`
So I'm passing data param `to collection.fetch`, now I need to catch this `myquery` from collection. I have no I idea how to do it.

**Comment by wyuenho** [comment]
``` javascript

// inside your view event handler
this.collection.queryParams.query = myquery;
this.collection.fetch();
```

**Comment by Integral** [comment]
Oh my goodness!
You know sometimes world seems so complicated... Thanks for showing that it isn't true! ;-)
