### ISSUE TITLE
Problem integrating into project 'undefined'

### ISSUE THREAD

**Issue by roberttolton** [backbone-paginator/backbone-pageable#58]
Apologies if this is seen as a stupid question, but I'm really unsure about where to ask for help regarding this plugin. I'm still learning.

I'm trying to integrate it with my Backbone project, using an AMD / Require.js approach as detailed here: http://backbonetutorials.com/organizing-backbone-using-modules/

I've got PageableCollection defined in my requirejs.config shim:

``` javascript
'PageableCollection': {
      deps: ['underscore', 'backbone'],
      exports: 'PageableCollection'
    }
```

As well as it's path set:
'PageableCollection'  : '../libs/backbone/backbonePageable', (correct path)

And then in my collection file I'm trying to use it:

``` javascript
define('ProjectCollection', [
  'jquery',
  'underscore',
  'backbone',
  'PageableCollection',
  'ProjectModel'
], function($, _, Backbone, PageableCollection, Project) {
  var ProjectCollection;

  ProjectCollection = Backbone.PageableCollection.extend({
    model : Project,
    url   : "/fuelmanager/api/projects",
     // Any `state` or `queryParam` you override in a subclass will be merged with
    // the defaults in `Backbone.PageableCollection` 's prototype.
    state: {

      // You can use 0-based or 1-based indices, the default is 1-based.
      // You can set to 0-based by setting ``firstPage`` to 0.
      firstPage: 0,

      // Set this to the initial page index if different from `firstPage`. Can
      // also be 0-based or 1-based.
      currentPage: 2,

      // Required under server-mode
      totalRecords: 200
    },
     // You can configure the mapping from a `Backbone.PageableCollection#state`
    // key to the query string parameters accepted by your server API.
    queryParams: {

      // `Backbone.PageableCollection#queryParams` converts to ruby's
      // will_paginate keys by default.
      currentPage: "current_page",
      pageSize: "page_size"
    }
  });

  return ProjectCollection;
});
```

But I just cannot get past an error:
projects.js:10TypeError: 'undefined' is not an object (evaluating 'Backbone.PageableCollection.extend')

I know I must be doing something wrong, perhaps it's obvious - but any ideas?

**Comment by wyuenho** [comment]
`backbone-pageable` is a separate dependency from backbone itself. You need to require it too but I don't see it in your config.

You should be able to just require `backbone-pageable` instead of `PageableCollection`, and `PageableCollection` will be available in the `Backbone` object.

**Comment by roberttolton** [comment]
Thanks for the reply, here's my full config now:

``` javascript

requirejs.config({
  shim: {
    'underscore': {
      exports: '_'
    },
    'backbone': {
      deps: ['underscore', 'jquery'],
      exports: 'Backbone'
    },
    'bootstrap': {
      deps: ['jquery'],
      exports: 'bootstrap'
    },
    'backbonePageable': {
      deps: ['underscore', 'backbone'],
      exports: 'PageableCollection'
    }
  },
  paths: {
    'text'              : '../libs/require/text',
    'jquery'            : '../libs/jquery/jquery',
    'underscore'        : '../libs/underscore/underscore',
    'backbone'          : '../libs/backbone/backbone',
    'backbonePageable'  : '../libs/backbone/backbonePageable',
    'bootstrap'         : '../libs/bootstrap/bootstrap',
    'bootstrapSwitch'   : '../libs/bootstrap/bootstrapSwitch',
    'bootstrapPager'    : '../libs/bootstrap/bootpag',
    'moment'            : '../libs/moment/moment',
    'JSON'              : '../libs/json/json2',
    'select2'           : '../libs/select2/select2',
    'App'               : 'app',
    'Router'            : 'router',
    'UserModel'         : 'models/user',
    'UserCollection'    : 'collections/users',
    'AlertsView'        : 'views/alerts',
    'ProjectModel'      : 'models/project',
    'ProjectCollection' : 'collections/projects',
    'ProjectListSidebarView'       : 'views/sidebar/project_list',
    'ProjectSidebarView'       : 'views/sidebar/project',
    'HomeView'          : 'views/home',
    'HomeSidebarView'   : 'views/sidebar/home',
    'ProjectListView'   : 'views/project/index',
    'ProjectView'       : 'views/project/show'
  }
});

require(['App'], function(App) {
  App.initialize();
});
```

**Comment by wyuenho** [comment]
`backbone-pageable` doesn't actually export anything. It just adds a new `PageableCollection` to the `Backbone` object. Just require it after you've required `Backbone` and you should be able to reference `Backbone.PageableCollection` from the `Backbone` object.

**Comment by roberttolton** [comment]
Where in my config should I require it? 
I tried it as a dependancy of backbone just to try, but that resulted in a require.js timeout. 

Not sure where to add it, sorry ^^;

**Comment by wyuenho** [comment]
In your own module, i.e. `ProjectCollection`. I'm pinging @jrburke on Twitter. Hopefully he can help you out.

**Comment by roberttolton** [comment]
Ah ok, I see. I've left it as just a path in my config:

``` javascript

requirejs.config({
  shim: {
    'underscore': {
      exports: '_'
    },
    'backbone': {
      deps: ['underscore', 'jquery'],
      exports: 'Backbone'
    },
    'bootstrap': {
      deps: ['jquery'],
      exports: 'bootstrap'
    }
  },
  paths: {
    'text'              : '../libs/require/text',
    'jquery'            : '../libs/jquery/jquery',
    'underscore'        : '../libs/underscore/underscore',
    'backbone'          : '../libs/backbone/backbone',
    'backbonePageable'  : '../libs/backbone/backbonePageable',
    'bootstrap'         : '../libs/bootstrap/bootstrap',
    'bootstrapSwitch'   : '../libs/bootstrap/bootstrapSwitch',
    'bootstrapPager'    : '../libs/bootstrap/bootpag',
    'moment'            : '../libs/moment/moment',
    'JSON'              : '../libs/json/json2',
    'select2'           : '../libs/select2/select2',
    'App'               : 'app',
    'Router'            : 'router',
    'UserModel'         : 'models/user',
    'UserCollection'    : 'collections/users',
    'AlertsView'        : 'views/alerts',
    'ProjectModel'      : 'models/project',
    'ProjectCollection' : 'collections/projects',
    'ProjectListSidebarView'       : 'views/sidebar/project_list',
    'ProjectSidebarView'       : 'views/sidebar/project',
    'HomeView'          : 'views/home',
    'HomeSidebarView'   : 'views/sidebar/home',
    'ProjectListView'   : 'views/project/index',
    'ProjectView'       : 'views/project/show'
  }
});

require(['App'], function(App) {
  App.initialize();
});
```

And then requiring it in my ProjectCollection like so:

``` javascript

define('ProjectCollection', [
  'jquery',
  'underscore',
  'backbone',
  'backbonePageable',
  'ProjectModel'
], function($, _, Backbone, backbonePageable, Project) {
  var ProjectCollection;

  ProjectCollection = Backbone.PageableCollection.extend({
    model : Project,
    url   : "/fuelmanager/api/projects",
     // Any `state` or `queryParam` you override in a subclass will be merged with
    // the defaults in `Backbone.PageableCollection` 's prototype.
    state: {

      // You can use 0-based or 1-based indices, the default is 1-based.
      // You can set to 0-based by setting ``firstPage`` to 0.
      firstPage: 0,

      // Set this to the initial page index if different from `firstPage`. Can
      // also be 0-based or 1-based.
      currentPage: 2,

      // Required under server-mode
      totalRecords: 200
    },
     // You can configure the mapping from a `Backbone.PageableCollection#state`
    // key to the query string parameters accepted by your server API.
    queryParams: {

      // `Backbone.PageableCollection#queryParams` converts to ruby's
      // will_paginate keys by default.
      currentPage: "current_page",
      pageSize: "page_size"
    }
  });

  return ProjectCollection;
});
```

It's still throwing:
(ProjectCollection) projects.js:10 TypeError: 'undefined' is not an object (evaluating 'Backbone.PageableCollection.extend')

Thanks for the continued help, it really is much appreciated ^^

**Comment by jrburke** [comment]
Assuming you are using this version:
https://github.com/wyuenho/backbone-pageable/blob/master/lib/backbone-pageable.js#L16

pageable calls AMD's define, so no shim config is needed, and it only attaches to Backbone for the "browser globals" case. For the AMD case, it just returns [PageableCollection](https://github.com/wyuenho/backbone-pageable/blob/master/lib/backbone-pageable.js#L1291), so it will not be accessible from Backbone.PageableCollection, but have a module exports value. 

In that case, if you have the paths config set up correctly, which you can check if paths config is set up in the dev tools network tab, ensuring there is no 404 for that file, then in a module that wants to use it, this should be enough:

``` javascript
define(['backbonePageable'], function (PageableCollection) {
  var ProjectCollection = PageableCollection.extend({});
});
```

**Comment by wyuenho** [comment]
Thanks @jrburke ! . That's what I should have said. I'm confused by require.js and I'm the one who put that code in. :P Sorry @fuelintegrated it's taken so long to answer your question.

@jrburke have you considered making require.js easier for people? Why can't r.js just scan the file system and automatically construct the paths config? Supplying paths overrides and shims should be considered advanced usage no? There are just too many moving parts to understand before anyone can start coding.

**Comment by jrburke** [comment]
@wyuenho I view paths configs as anti-patterns. It is possible to construct project layouts that do not need them. Part of the trouble is the breadth of personal preferences on code layout for front end projects. This is my ideal project setup:

https://github.com/volojs/create-template

baseUrl is set to the lib directory, where third party code goes, and there is one paths config to point the "app" module space to the right place. If [volo](http://volojs.org) is used to fetch dependencies, it lays out the code correctly if the package.json has a volo.baseUrl, which happens correctly if the above template is used for `volo create`.

I need to update the requirejs starter docs to start encouraging this path. There are still some wrinkles around shim config dependencies, but still the above is a good place to start.

**Comment by roberttolton** [comment]
Thanks for replying!

So I just have to update this line, awesome!

``` javascript
ProjectCollection = PageableCollection.extend({
```

I'll try this when I get back into work on Tuesday and update ^^
Thanks again guys.

**Comment by roberttolton** [comment]
Looks like it's working now - XHR's showing page_size and current_page parameters being sent - now to configure the rest!

Thanks for the help guys.

**Comment by halcyonandon** [comment]
I'm curious if this works with server-side sorting. I ran into the same issue with requireJS and used the same solution. The problem occurs on line 1830 of backgrid.js

``` javascript
    if (Backbone.PageableCollection && collection instanceof Backbone.PageableCollection) {
```

because the solution:

``` javascript
ProjectCollection = PageableCollection.extend({
```

It won't catch that condition and sorting will instead execute:

``` javascript
      collection.comparator = comparator;
      collection.sort();
```

I think I recall a thread where someone found a way to get out of this situation by adding PageableCollection to Backbone in the config... trying to find that

**Comment by halcyonandon** [comment]
Solved here https://github.com/wyuenho/backbone-pageable/issues/62
