### ISSUE TITLE
question: Paginator problem in client mode

### ISSUE THREAD

**Issue by isrd1** [backbone-paginator/backbone-pageable#60]
Hello,

I'm using backgrid, with require.js, it's working very well.  However, when I try to use paginator in client mode I get an error on line 104 in the resetQuickly method that the collection is undefined.  Tracking this back the call comes from 1095 where resetQuickly is called passing in fullCollection which, in turn comes from line 1079 this.fullCollection.  It would appear from my debugger that 'this' is undefined.  Can you suggest what might be going wrong please, I've spent some hours getting no where?

A clue might be that in my Collection class I'm finding that Backbone.PageableCollection is undefined but PageableCollection exists.  I thought that perhaps the .call wasn't therefore assigning 'this' correctly.  I've tried a simple:
        if (!Backbone.PageableCollection) Backbone.PageableCollection = PageableCollection;
But that didn't help.
Any ideas please?
Thanks, Rob

Actually the problem would appear to be that I had an initialize method in my collection class, and that was called by backbone instead of the PageableCollection.initialize, consequently I didn't have things like fullCollection.

**Comment by wyuenho** [comment]
Line 1079 is an empty line on master. Which version are you using? Can you update to 1.2.0 and post a stacktrace if you still have this problem?

**Comment by atishn** [comment]
I just had same issue yday. I created an issue yday which I closed with solution.

Please refer...  

https://github.com/wyuenho/backbone-pageable/issues/61
