### ISSUE TITLE
Pagination not working in Client Mode.

### ISSUE THREAD

**Issue by atishn** [backbone-paginator/backbone-pageable#61]
Hi,
My REST api doesnt have any facility for paginating results. It always returns the full stack of resource.

Hence I decided to use client mode for pagination.

While using I see this issue, backbone-pageable( 1.2.0) version at following line

var t = arguments[0], r = e.toArray(arguments).slice(1), a = t.comparator;

I see arguments[] hase 3 enteries.
0- null
1- Array of 72 Person Model objects.
2- Some object.

And the above line of code is breaking due to direct access of t.comparator which is being null.

I am extending the PageableCollection using require.js framework.

define([
    'jQuery',
    'lodash',
    'Backbone',
    'data/models/personModel',
    'backbonePageable'
], function ($, _, Backbone, personModel, PageableCollection) {
    var collection = PageableCollection.extend({

 model: personModel,
        url: window.app.SERVICE_BASE_PATH + '/person',

```
    initialize: function () {
        // Default sort field and direction
        this.sortField = "firstName";

    },

    mode: "client",

    comparator: function (m) {
        return m.get(this.sortField);
    },

});

return collection;
```

});

After reading through backbone-pageable.js , I found we need to instantiate the PageCollection with Arguments explicitly.

```
        PageableCollection.prototype.initialize.apply(this, arguments);
```

So this line of code worked.

define([
    'jQuery',
    'lodash',
    'Backbone',
    'data/models/personModel',
    'backbonePageable'
], function ($, _, Backbone, personModel, PageableCollection) {
    var collection = PageableCollection.extend({

 model: personModel,
        url: window.app.SERVICE_BASE_PATH + '/person',

```
    initialize: function () {
        // Default sort field and direction
        this.sortField = "firstName";
        PageableCollection.prototype.initialize.apply(this, arguments);

    },

    mode: "client",

    comparator: function (m) {
        return m.get(this.sortField);
    },

});

return collection;
```

});

This is just for reference to some one who is using this awesome api using require.js

**Comment by atishn** [comment]
It seems if implementing class has constructor method initialize(), it must call parents parents initialize() method to get it resolved.

**Comment by wyuenho** [comment]
You don't need to call the superclass' initialize. As you can see from [Backbone's source code](https://github.com/documentcloud/backbone/blob/master/backbone.js#L616). Collection#initialize is empty.

**Comment by atishn** [comment]
Yes, Backbone Collection initialzie method is empty, but not PageableCollection which I was referring in my comment. Sorry if its mistaken.

So when some extend the PageableCollection and overwrite initialize method, they must need to give call PageableCollection initialize() method otherwise they end up in strange issues.

PageableCollection.prototype.initialize.apply(this, arguments);

I think this is a point worth needs to be added in documentation.
Thanks for your kind reply.
