### ISSUE TITLE
Requirejs Integration Problems

### ISSUE THREAD

**Issue by p-clark** [backbone-paginator/backbone-pageable#62]
This is a continuation of the issue reported by fuelintegrated: #58 

I am able to pull in the PageableCollection correctly into my require.js project in a similar manner to fuelintegrated.  Everything works fine with backgrid, except for sorting.  I am using server mode and as a result it appears that the namespacing of Backgrid.PageableCollection in the HeaderCell sort function is causing a server side sort not to happen.

This is the code snippet that is causing me problems from backgrid.js (starting at line 1617):

```
if (Backbone.PageableCollection && collection instanceof Backbone.PageableCollection) {
  var order;
  if (direction === "ascending") order = -1;
  else if (direction === "descending") order = 1;
  else order = null;

  collection.setSorting(order ? columnName : null, order);

  if (collection.mode == "client") {
    if (!collection.fullCollection.comparator) {
      collection.fullCollection.comparator = comparator;
    }
    collection.fullCollection.sort();
  }
  else collection.fetch();
}
else {
  collection.comparator = comparator;
  collection.sort();
}
```

However, if I modify the code to do this:

```
if (collection.mode == "server") {
  var order;
  if (direction === "ascending") order = -1;
  else if (direction === "descending") order = 1;
  else order = null;

  collection.setSorting(order ? columnName : null, order);

  if (collection.mode == "client") {
    if (!collection.fullCollection.comparator) {
      collection.fullCollection.comparator = comparator;
    }
    collection.fullCollection.sort();
  }
  else collection.fetch();
}
else {
  collection.comparator = comparator;
  collection.sort();
}
```

It does the server side sorting correctly.  I also wanted to note that this only started happening to my application when I migrated it to requirejs.  Which leads me to believe it is something related to the namespace of required objects.

The code I submitted is clearly not the final solution, but wanted to demonstrate how I tracked down the problem and hacked it to get it working.

**Comment by wyuenho** [comment]
You are correct that if you require backbone-pageable from require.js, PageableCollection will not be available on the Backbone object. The easiest way to fix it is to manually attach PageableCollection to Backbone in your initialization code.

FYI, Backgrid doesn't support AMD at the moment so there's no consideration made for being compatible with it.

**Comment by p-clark** [comment]
Thank you for the information wyuenho.  Here is what I did in my requirejs module that appears to have worked:

define(['jquery', 'underscore', 'backbone', 'backbone-pageable'], function($, _, Backbone, PageableCollection) {

```
Backbone.PageableCollection = PageableCollection;
```

...
}

Thanks for the assistance and a great library!
