### ISSUE TITLE
Pagination - Sorting in client Mode

### ISSUE THREAD

**Issue by atishn** [backbone-paginator/backbone-pageable#63]
Hi,

I am using pagination with client mode

   // Initial pagination states
        state: {
            pageSize: 30
        },

```
    mode: "client"
```

I see an issue while sorting a page. It seems collection is getting sort only on page and its not sorting the whole collection.

For eg.

If I sort first page, I expect to see the data listing on last page and vice a versa.

But my table is only sorting all entries of current page and displaying it back rather than having full collection sort.

Please help me.

**Comment by wyuenho** [comment]
How are u doing the sorting now? If you use `setSorting` the comparator will be set on the `fullCollection` by default in client mode.

https://github.com/wyuenho/backbone-pageable#sorting

**Comment by atishn** [comment]
I am using default sorted in collection itself.

My configuration is very simple and straight forward. But for all columns while clicking header for sort, it seems it only does page sorting and not full collection sorting.

define([
    'jQuery',
    'lodash',
    'Backbone',
    'data/models/personModel',
    'data/collections/base/pageableCollection'
], function ($, _, Backbone, personModel, PageableCollection) {
    var collection = PageableCollection.extend({
        model: personModel,
        url: window.app.SERVICE_BASE_PATH + '/person',
  // Initial pagination states
        state: {
            pageSize: 30
        },
        mode: "client"
        comparator: function (m) {
            return m.get("companyName");
        }
}

var columns =
{
                        name: "companyName",
                        label: "Company",
                        editable: false,
                        cell: Backgrid.StringCell.extend({
                            render: function () {
                                this.$el.empty();
                                var company = this.model.get("company");
                                if (company) this.$el.append(company.name);
                                return this;
                            }
                        })

```
                },
                {
                    name: "phone",
                    label: "Phone",
                    cell: "string",
                    editable: false
                },
                {
                    name: "email",
                    label: "Email",
                    cell: "string",
                    editable: false
                }


            this.grid = new Backgrid.Grid({
                columns: this.getColumns(),
                collection: this.getTableCollection(),
                footer: this.getFooter()
            });
```

**Comment by wyuenho** [comment]
If you use a comparator, it will only sort the current page under client mode. You have to either attach the comparator to `fullCollection` or use the `setSorting` method instead.

**Comment by atishn** [comment]
Thanks for your quick response.

I removed default comparator used in collection.

Now with plain implemenation, which is quite similar to paginator section of
http://wyuenho.github.com/backgrid

There I dont see any code which either using setSorting or fullCollection.

Do I still need to write if-else conditions logic in my code to find out which column header click and call setSorting of that column name to full collection or backbone-pageable will do it.

I assume backbone-pagable should do it by itself as it is doing in above sample example listed.

**Comment by wyuenho** [comment]
The data is already sorted in that example. Sorting by column is enabled by default, no extra code needed.
