### ISSUE TITLE
getPage concatenates 1 as a string instead of adding

### ISSUE THREAD

**Issue by kooliokey** [backbone-paginator/backbone-pageable#64]
I was having a problem with changing pages using BackGrid and tracked the problem back to line 830 of backbone-pageable.js.

When I click "Next Page" on the grid pager it concatenates 1 to the currentPage because I guess currentPage gets set as a string somewhere along the line. 

Ex: I'm on page 31, next page is 32, but the script told it to go to page 311. 

I put:

``` javascript
case "next": pageNum = parseInt(currentPage) + 1; break;
```

on line 830 of backbone-pageable.js, but it may be better to put it wherever the currentPage is being set as a string.

I am also using server mode if that helps track down a better place to fix the string issue.

**Comment by wyuenho** [comment]
The correct solution is to never send down strings from the server when they should be numbers. Even if I cast the value to a number here, I still can't prevent you for doing something weird like sending down `lastPage: "31"`. It's javascript, you just have to deal with type issues like this.

**Comment by kooliokey** [comment]
Yeah I didn't realize it was because my server-side script was sending it as a string. It was taking it straight from the $_GET variable that was passed from the grid, so I just casted it to an integer before it sends it back. Thanks
