### ISSUE TITLE
Bower pulls old release -- need version bump

### ISSUE THREAD

**Issue by bryanbuchs** [backbone-paginator/backbone-pageable#65]
Bower is still pulling an older commit as your release version.  Your component.json lists the version as "1.2.0", and that matches your tag for a commit from 2 weeks ago (2013-03-20). 

If you create a new tag ("1.2.1") and update component.json, bower will pull the matching release.

I can do a pull request with the component.json update, but I am not sure if/how the tagging works with a fork/pull request.

**Comment by wyuenho** [comment]
Mmmm. There's nothing done after releasing 1.2.0. I think you mean I need to relax Backbone's version constraint right?

**Comment by wyuenho** [comment]
component.json updated.

**Comment by bryanbuchs** [comment]
No, sorry if I wasn't clear. 

Bower uses commits from the most recent tag in your repo. So when I do a `bower install backbone-pageable`, I'm essentially running `git pull` and then `git checkout 1.2.0`. 

In your `component.json` the backbone-pageable version should be bumped up to:

`"version": "1.2.1",`

**But you'll also need to create a new tag that matches that release in git and push that to github.**

If you don't want to call the changes between 1.2.0 and now a "new release", I suppose you could remove the original "1.2.0" tag and replace it with a new "1.2.0" tag that points to a newer commit SHA.

**Comment by wyuenho** [comment]
Where do you see this version 1.2.1 that you speak of? I haven't work on backbone-pageable in weeks and there's no plan to release a next version. Do u have something that u want me to incorporate into a new version?

**Comment by bryanbuchs** [comment]
I'm saying that in order to play friendly with Bower and other package managers, you should create a new release/tag that points at a newer commit. If you don't, then Bower will continue to pull -- or in the case of any Windows users, attempt and fail to pull -- your 1.2.0 release/tag (fab6feaf91).

The last 6 commits are not part of "1.2.0", which is what your `component.json` file specifies.  One of those commits was my pull request to fix the issue (#47) with filename errors on Windows systems.

Until you create a new git tag -- I suggested "1.2.1", but call it whatever you want! -- then Bower will use the "1.2.0" tag. That tag/release still contains illegal filenames (like `territories.json?page=1&per_page=15`).

**Comment by wyuenho** [comment]
Ah ok my mistake. I just retagged. You should be able to check out 1.2.0 from bower now.

**Comment by wyuenho** [comment]
Mmm. Hold on, it seems bower is still caching the old tag.... grrr

**Comment by wyuenho** [comment]
Ok it look like the bower package list is updated every 60 minutes so in about 40min you should be able to bower install the most updated tag. Ping me if it still doesn't work.

**Comment by wyuenho** [comment]
FYI, you should delete the old cached packages from ~/.bower or wherever bower caches its packages on Windows. It seems it won't fetch backbone 1.0 if 0.9.10 satisfies backbone-pageable's dependency.

**Comment by bryanbuchs** [comment]
Outstanding, that's working nicely now. Thanks for your help and cooperation.
