### ISSUE TITLE
support for jsonp &callback=?

### ISSUE THREAD

**Issue by tony** [backbone-paginator/backbone-pageable#66]
This worked in my normal Backbone collection.

```
    url:  '/api/stream?callback=?',
```

http://api.jquery.com/jQuery.ajax/

This is where adding `callback=?` will have jquery create a fresh jsonp callback variable.

So I was pleased to see I could add variables to `queryParams`:

``` javascript
querParams: {
      callback: '?'
}
```

Unfortunately, for some reason the `?` in the `callback` is included. I can't quote find what's encoding it.  Any ideas?

**Comment by wyuenho** [comment]
I'm not sure what you are trying to accomplish. The URL has 2 `?`, everything after the first `?` is put into `$.ajax` as data, the final URL is constructed by jQuery, so if it's encoded, that's because jQuery encoded it. Why can't you just specify a callback instead of a placeholder?

**Comment by wyuenho** [comment]
BTW, you can override anything by supplying [`options.data`](http://backbonejs.org/#Collection-fetch) to any of the fetch methods in Backbone.PageableCollection.
