### ISSUE TITLE
AMD wrapper style

### ISSUE THREAD

**Issue by tony** [backbone-paginator/backbone-pageable#67]
AMD support isn't working as expected for me.

I expect that including Backbone in a define will append it `Backbone.PageableCollection`.

In practice, however, the `else if (typeof define == "function" && define.amd) {` is being caught in browser, so the else if below is never ran.

In the past few months I have made great use of [Backbone Marionette](https://github.com/marionettejs/backbone.marionette)'s AMD wrapping style, as it has the expected functionality, http://marionettejs.com/downloads/core/amd/backbone.marionette.js.

I believe that https://github.com/umdjs/umd may be the most thoroughly tested way to implement this.

Thoughts?

**Comment by wyuenho** [comment]
See #58
