### ISSUE TITLE
Infinite mode demo is broken

### ISSUE THREAD

**Issue by dandavison** [backbone-paginator/backbone-pageable#68]
Looks like changes to github pages have broken the demo:

http://wyuenho.github.io/backbone-pageable/examples/infinite-mode.html

->

![image](https://f.cloud.github.com/assets/52205/346945/f983cfa6-9e7f-11e2-8656-61b77c7055cb.png)

See https://github.com/blog/1452-new-github-pages-domain-github-io

**Comment by wyuenho** [comment]
That infinite paging mode demo really needs to be rewritten and the default `parseLinks` implementation changed to something that works on all browsers. This will fix #44 too.

**Comment by wyuenho** [comment]
Fixed by authorizing the .io domain from the github app
