### ISSUE TITLE
parseRecords getting called twice

### ISSUE THREAD

**Issue by JoshClose** [backbone-paginator/backbone-pageable#71]
I have overridden parseRecords because the data being returned is an object with an array on it.

The data being returned:

``` javascript
{
   Data: []
}
```

Normally in backbone I would just do this:

``` javascript
parse: function(response) {
   return response.Data;
}
```

parseRecords is getting called twice. The first time it is giving me the data from the server, but the second time it gives me the array of models that I returned from the first call.

Is this expected behavior or am I doing something wrong? It seems odd to me.

I'm able to workaround it by doing this:

``` javascript
parseRecords: function(response) {
    return response.Data || response;
}
```

**Comment by wyuenho** [comment]
`parseRecords` shouldn't be called twice unless `parse` is being called twice. Did you set `options.parse` to true somewhere?

**Comment by JoshClose** [comment]
No. The collection is really simple. I don't have the code in front of me at the moment and can put exact code tomorrow, but it looked something like this.

``` javascript
var MyCollection = Backbone.PageableCollection.extend({

    model: MyModel, // This may or may not be there.

    url: "/some/path",

    parseRecords: function(response) {
        return response.Data || response;
    },

    save: function() {
        return this.sync("update", this);
    }

});
```

I'm pretty sure that's all that's in there, but I will double check that tomorrow.

**Comment by JoshClose** [comment]
The only thing I missed from the code above is `mode: "client"`. The model property IS there also.

**Comment by JoshClose** [comment]
I have this exact same thing somewhere else that doesn't have `mode: "client"` and `parseRecords` is only hit once in that case.

**Comment by nemeria** [comment]
Same issue with mode: "infinite".
And the second time parseRecords is called my models are nested in the attributes of new models. 
For example on the second parseRecords I have :

```
models[0] = { 
    changing: fase, 
    _events: Object, 
    attributes: {
       changing: false,
       _events: object,
      attributes: {
          //right attributes
      }
    }
    ...
}

```

**Comment by wyuenho** [comment]
Can you see if you can reproduce this problem on Backbone 0.9.10?

**Comment by nemeria** [comment]
I think the issue comes from https://github.com/documentcloud/backbone/blob/master/backbone.js#L860

which was not present in the 0.9.10, i cannot test it, i have some errors before ^^
