### ISSUE TITLE
Server mode example doesn't response to sorting

### ISSUE THREAD

**Issue by Integral** [backbone-paginator/backbone-pageable#72]
It seems that server sorting is not working with backbone 1.
No errors and no sorting until replacement to 0.9.10

**Comment by wyuenho** [comment]
The demo just serves static files straight from Github Pages, so it can't really do "server-side sorting" as there's not really a server that does sorting.

If it's really not working on a real server, I'd really appreciate it if you could tell me exactly how and why it's not working, steps to reproduce it etc, as outlined in the CONTRIBUTING.md document. This will speed up the bug fixing process tremendously.

**Comment by Integral** [comment]
Ok, that's link to zip: https://docs.google.com/file/d/0B-4PSkYLKeoTMV82WnUxUFZOLXc/edit?usp=sharing
Here you can find examples folder from this repo with backbone v1 and changed server-mode.html to work with real server-side example.

**Comment by wyuenho** [comment]
Thanks. Issue confirmed. Will roll out a fix shortly.

**Comment by Integral** [comment]
Thank you ;)

**Comment by wyuenho** [comment]
From the console it seems like the collection is getting sorted correctly but apparently Backgrid isn't. It's UI bug.
