### ISSUE TITLE
Client Side Pagination

### ISSUE THREAD

**Issue by markus101** [backbone-paginator/backbone-pageable#78]
I just started using backbone-pagable 1.2.2 with backgrid in a client side scenario and have a couple questions about its usage.

For this particular table I do not want paging, but want to take advantage of PageableCollection's sorting functionality.

1) Is there a way, besides setting enormous number for the pageSize to disable paging? I've tried, 0, null & undefined, which result in various errors, not opposed to setting a very large page size, but would find it more readable to set a proper value.

2) In client mode is there a reason why sort_by and order are sent to the server? My server is ignoring them, but I'd prefer they not be sent at all, unless there is a reason why they are? For reference this is where they seem to get added in the unminified release: 
[1103](https://github.com/wyuenho/backbone-pageable/blob/master/lib/backbone-pageable.js#L1103)

Thanks for the work on these great backbone extensions!

**Comment by wyuenho** [comment]
1) Not under client mode. Why would you want to disable pagination in a PageableCollection? If you just want to sort then shouldn't you just use Backbone.Collection instead?
2) You can set queryParams.sortKey and queryParams.order to null to not sent them at all.

**Comment by markus101** [comment]
1) Mostly for the sorting, instead of copying that out into another collection, but valid point, since it does seem a bit awkward.

2) Just tested this, looks like when order is set to null it uses 'null' as the parameter name in the query string.

**Comment by wyuenho** [comment]
2) My mistake. Actually `queryParams.sortKey` and `queryParams.order` are only sent in the URL's query params if `state.sortKey` is not null, that means you need to [turn off sorting](https://github.com/wyuenho/backbone-pageable#sorting).

It actually sounds like you don't need any functionality PageableCollection provides. Aren't you sure it won't be easier to just use a plain Backbone.Collection?

**Comment by markus101** [comment]
No problem, in this case yes, a plain Backbone.Collection will suffice. Thanks for you time and again, great work.
