### ISSUE TITLE
Append next page data to collection in 'server' mode

### ISSUE THREAD

**Issue by svr** [backbone-paginator/backbone-pageable#79]
Is there an easy way to make backbone-pageable to append next page data to current collection in 'server' mode?
I'd like to use backbone-pageable for creating so-called 'endless scrolling pagination' and keep appending new data from server.
I tried using 'infinite' mode but couldn't make it append, not reset collection,
'infinite' mode demo
http://wyuenho.github.io/backbone-pageable/examples/infinite-mode.html
also does not seem to append new data to current collection.
Maybe additional option to switchMode() could be usefull here?

**Comment by wyuenho** [comment]
Instead of using the current collection under infinite mode, you can use the fullCollection instead. New pages are appended to fullCollection instead of being reset.

**Comment by svr** [comment]
Thank you. I was thinking about something like that, but wasn't sure.
In order to make it work thе way I need, had to make some changes to backbone-pageable

``` javascript
422c422
<           ++state.totalRecords;
---
>           //++state.totalRecords;
495c495
<             if (!(state.totalRecords = fullCol.models.length)) {
---
>             if(!state.totalRecords){
```

Just to make it work like in 'server' mode but not overriding state.totalRecords and get it directly from server. 
Not sure what pitfalls that could have...

Anyway thank you for backbone-pageable. 
Nice work!

**Comment by josx** [comment]
@svr  I was searching the same thing as you. An endless mode working like server.
I have cloned bb-pageable and do in it for my project, take a look here:
https://github.com/inaes-tic/backbone-pageable/commit/02c976d32cab256692d081145a3dd448b29b13f9

**Comment by wyuenho** [comment]
@svr If you could apply your changes to infinite mode only, I'll accept it. Right now you've changed the behavior for client mode too.

@josx If you can't use fullCollection for some reason, as you've discovered, the easiest way to do what you want would be to call `getNextPage({remove: false})`. There's no need to add another mode.
