### ISSUE TITLE
How to implement endless scrolling?

### ISSUE THREAD

**Issue by vjpr** [backbone-paginator/backbone-pageable#80]
Firstly, awesome library! Made standard pagination trivial - great docs too. Much easier to use than Backbone.Paginate.

At the moment I am using `setPageSize` on a scroll event. This requires a re-render of the entire collection which is sub-optimal.

Is there a way I can call `getNextPage()` and have the results trigger `add` events on my Collection to make the endless scrolling experience (a la Facebook news feed) better?

So far I have:

```
    # Scrolling.
    @isLoading = false
    buffer = 200
    $window = $(window)
    $window.scroll =>
      console.log 'offset', @$el, @$el.offset()

      # Before the bottom of the viewport...
      bottomOfViewport = $window.scrollTop() + $window.height()
      # passes the bottom of the list of elements minus a buffer...
      bottomOfCollectionView = @$el.offset().top + @$el.height() - buffer
      # we should re-render.

      if not @isLoading and bottomOfViewport > bottomOfCollectionView
        console.log 'loading more!!!!'
        currentPageSize = app.collections.props.state.pageSize
        @isLoading = true
        app.collections.props.setPageSize(currentPageSize + 10).done =>
          @isLoading = false
```

**Comment by vjpr** [comment]
I seem to have got it working by making my `view` listen to the `add` event on the `collection.fullCollection` property, and calling `collection.pageableCollection.getNextPage(silent: false)` to get my models.

@wyuenho is this the right approach?

Code attached (using Backbone.Marionette):

```
    app.views.collectionView = new CollectionView
      collection: new B.PageableCollection().fullCollection
```

```
class CollectionView extends Backbone.Marionette.CompositeView

  _initialEvents: =>  
    return unless @collection?
    @listenTo @collection, "add", @addChildView, this
    @listenTo @collection, "remove", @removeItemView, this

  onRender: =>

    # Scrolling.
    @isLoading = false
    buffer = 200
    $window = $(window)
    $window.scroll =>

      # Before the bottom of the viewport...
      bottomOfViewport = $window.scrollTop() + $window.height()
      # passes the bottom of the list of elements minus a buffer...
      bottomOfCollectionView = @$el.offset().top + @$el.height() - buffer
      # we should re-render.

      if not @isLoading and bottomOfViewport > bottomOfCollectionView
        console.log 'Loading more results'
        @isLoading = true
        @collection.pageableCollection.getNextPage(silent: false).success (data, status, jgXHR) =>
          @isLoading = false
```

**Comment by wyuenho** [comment]
The `this` at the end of `listenTo` is unnecessary. `silent: false` is also unnecessary because as soon as a new page is loaded from the server the entire fullCollection is `reset` with the appended records. However if you want to listen to the `add` event so you can append the records individually to the DOM instead of a whole page at a time, that's the right approach.

**Comment by vjpr** [comment]
Thanks. My approach now seems problematic as the models being rendered will differ from the fullCollection which will cause problems with other event bindings.

It would be nice if there were an option to set in backbone-pageable to allow such adding instead of reset functionality.

**Comment by vjpr** [comment]
Just had another look at the code. In infinite mode the models are added to fullCollection and only an event is triggered. So my approach might not be so problematic after all.

```
            fullCollection.add(models, _extend({at: fullCollection.length,
                                                silent: true}, opts));
            fullCollection.trigger("reset", fullCollection, opts);
```

Perhaps another mode could be added called `endless`, which adds records to collections instead of reset?

**Comment by wyuenho** [comment]
Can you elaborate? What problems do you have? I'll add a note for listening to the `add` event under infinite mode in the README.

**Comment by vjpr** [comment]
I feel that endless scrolling is a common UI pattern these days (thanks to the Facebook style news feed) that lots of people will be looking for.

Its jarring and laggy if the entire collection is reset each time a new chunk is pulled from the server. This is the default behaviour someone gets when implementing backbone-pageable.

The current way I have implemented it seems hacky and was not easy to work out.

When I heard `infinite` I thought it meant infinite _scroll_ which is slightly misleading as the most popular jquery endless scrolling plugin is called 'infinite-scroll', which is not what this plugin offers out-of-the-box.

I expected to be able to enable `infinite` mode and just bind to the collection and call `getNextPage` to add models.

**Comment by wyuenho** [comment]
Ah ok. So yes, backbone-pageable is not a UI component per-se, I've never advertised it as such. You do have to implement your own UI logic.

There are two reasons resetting is the default - 1) to remain compatible with Backbone < 1.0, and 2) adding individual DOM elements one by one will result in some quite noticeable popping of a list/table and lots of repaints if you are not careful. The way I do it usually is to surround the list/table inside a fixed height container with `overflow: scroll` and `visibility: hidden` on the newly added elements, so the newly appended elements will be hidden initially. Once all the DOM nodes have been appended into the DOM, I scroll up some pixels and then fade in the new elements.

**Comment by wyuenho** [comment]
I've added a note into the README in master now. Let me know if there's anything more you'd like me to clarify.

**Comment by josx** [comment]
@wyuenho I cant listen to fulllcollection and then add to collection, or use fullcollection instead (beacuse i am using it on knockout/knockback views)

@vjpr I have added an endless mode working like server on my cloned version
https://github.com/inaes-tic/backbone-pageable/commit/02c976d32cab256692d081145a3dd448b29b13f9

**Comment by chris-h-sg** [comment]
This is very useful! Any chance this could get pulled into master?

**Comment by josx** [comment]
After doing this I have read in another issue that you can do:

```
collection.getNextPage({remove: false});
```

To accomplish the same without changing backbone-pageable 's code.

**Comment by chris-h-sg** [comment]
Ah, that's nice. Thank you.

**Comment by amolinaalvarez** [comment]
@josx what mode did you use: server, client or infinite? I have just used
<code>
collection.getNextPage({remove: false});
</code>
in the infinite mode I did not get the expected behavior.
