### ISSUE TITLE
best practice for server mode

### ISSUE THREAD

**Issue by chirag04** [backbone-paginator/backbone-pageable#85]
I'm trying to implement pagination with this module in server mode.

While bootstrapping pageable collection i dont know totalRecords. Also the server api is not returning total records. 

How do i handle this case? Do i make a query to get the totalRecords before bootstrapping the pageable collection?

**Comment by wyuenho** [comment]
Yes. If you webpage is generated on the server from a template, you should bootstrap the collection by pasting the generated JSON into the constructor and setup the initial state by providing at least `totalRecords`.

If your server API doesn't return a `totalRecords` or equivalent, you can fetch a `totalRecords` from the server first, which means you still have to modify your server somehow to return that, or consider using infinite pagining mode.

**Comment by chirag04** [comment]
Thanks! Yes i will fetch `totalRecords` and add that method to fetch in the server API.
