### ISSUE TITLE
Sorting a Backbone-Pageable Collection in Client mode only sorts active page?

### ISSUE THREAD

**Issue by rabbitfufu** [backbone-paginator/backbone-pageable#86]
Hello,

I am using a backbone-pageable collection along with backgrid, in client mode, to create a pageable backgrid.

When I click on a column header, only the results on the active page are sorted.  My understanding from the documentation is that the entire collection should be sorted -- and this is the behaviour I desire. 

I define my collection like so:

<pre>
    var MyCollection = PaginatedCollection.extend({

        model: MyModel,
        url: "/anurl",
        state: {
            pageSize: 15
        },
        mode: "client"

    });
</pre>

And I initialize the backgrid like so:

<pre>
       var grid = new Backgrid.Grid({
        row: Row,
        columns: columns,
        collection: this.myCollection
    });
</pre>

Could you let me know what I am doing wrong?

Thank-you!

**Comment by wyuenho** [comment]
Nothing as far as I can tell. The only reason I can think of where full collection sorting will fail is when this.myCollection is not an instance of Backbone.PageableCollection.

**Comment by rabbitfufu** [comment]
Thanks - I figured it out.  The trouble was that I am using RequireJS to load modules, which does not automatically create Backbone.PageableCollection.  Once I manually set it up, everything works great.  Thanks for this great tool!

<pre>
define([
    "backbone",
    "pageablecollection"
    ], function( Backbone, PageableCollection ) {
    Backbone.PageableCollection = PageableCollection;
    var MyCollection = Backbone.PageableCollection.extend({ ... });
});
</pre>
