### ISSUE TITLE
setPageSize() with empty collection raises exception in _checkState

### ISSUE THREAD

**Issue by bazineta** [backbone-paginator/backbone-pageable#93]
Calling setPageSize() in the case of an empty collection results in currentPage being NaN, which in turn raises an exception in _checkState.  One easy solution appears to be simply appending '|| 1' to the end of the currentPage calculation in setPageSize().

**Comment by wyuenho** [comment]
Will just settings the pageSize directly to the state when totalRecords = 0 be an acceptable solution?

**Comment by bazineta** [comment]
I believe so; everything else in the state should be invariant at that point.

**Comment by bazineta** [comment]
Alternately, the following change to the calculation will avoid the division by zero issue, leaving the remainder of the function unchanged, including the automatic fetch and callback, etc.

```
  var state       = this.state;
  var totalPages  = ceil(state.totalRecords / pageSize);
  var currentPage = totalPages ?
                    max(state.firstPage,
                        floor(totalPages *
                              (state.firstPage ?
                               state.currentPage :
                               state.currentPage + 1) /
                              state.totalPages)) :
                    state.currentPage;
```

**Comment by wyuenho** [comment]
When totalPages is falsy, it is assumed to be 0 and current page will be reset back to firstPage.
