### ISSUE TITLE
Saving model state on server paging

### ISSUE THREAD

**Issue by JoshClose** [backbone-paginator/backbone-pageable#94]
In client mode when you make changes to a page (in backgrid) and page around, the changed cells are still there when you come back to that page. I'm guessing there is a second internal collection that has all the results or something.

I would like this same sort of behavior when doing server side paging.

Currently I'm implementing this myself by saving any changes to model state, and when paging reapplying any changes to models that are on that page. There would need to be a way to get all the changes that have happened also.

If this isn't recommended behavior because the models are supposed to save upon change, I can understand. Backbone.Collection doesn't have a save method because of that reason.

**Comment by wyuenho** [comment]
Backbone's issue tracker has a number of discussions as to why there are no batch operations built in. Generally they all come down to that HTTP doesn't really define a way to do batch updates.

There is also no difference whether you do this on server or client mode. You can still save and force a fetch under client mode.

**Comment by JoshClose** [comment]
As far as the client goes, I meant there is an underlying collection that has all of the changes, and when you go to the server in server mode, that isn't the case, so all those changes get wiped out.

Not a big deal; I understand why it's not available. It's pretty easy to implement it anyways.
