### ISSUE TITLE
Consistent way to know when a collection has fetched

### ISSUE THREAD

**Issue by JoshClose** [backbone-paginator/backbone-pageable#95]
Is there a consistent way to know when a collection (PageableCollection) behind a Backgrid has fetched? When doing paging an `add` event gets fired for every row. When sorting a `reset` event gets fired once.

I need to do something any time the collection has gone to the server and got a new set of results. The sorting and paging is being done through backgrid, so I'm not calling the methods myself and don't have a handle on the xhr.

**Comment by wyuenho** [comment]
Listen to the `sync` event on `pageableCollection#fullCollection` under client mode, or just the `collection` itself.
